# Expanded Q4 2025 AI/Tech Earnings Evaluation

This notebook runs the full 55-name Q4 2025 AI/Tech earnings evaluation in one clean flow:

1. Load repo settings and cache paths
2. Build the post-earnings price evaluation table
3. Load or refresh cached agent packets
4. Run missing or forced CIO workflows incrementally
5. Rebuild `cio_eval` from cached CIO workflows
6. Compare CIO against single agents and GPT/Gemini/Claude external baselines

Default settings reuse cache and avoid expensive LLM reruns. Change the flags in the config cell when you intentionally want to refresh outputs.

In [37]:
import os
import sys
import importlib
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from IPython.display import display, Markdown

CURRENT_DIR = Path.cwd().resolve()
REPO_ROOT = CURRENT_DIR if (CURRENT_DIR / "pyproject.toml").exists() else CURRENT_DIR.parent
SRC_PATH = REPO_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

load_dotenv(REPO_ROOT / ".env", override=True)

from openclam.evaluation import q4_earnings_cache as q4
from openclam.agents.news_macro import news_macro_agent

q4 = importlib.reload(q4)

print(f"Repo root: {REPO_ROOT}")
print(f"Loaded q4 module: {q4.__file__}")
print(f"VERTEX_PROJECT loaded: {bool(os.getenv('VERTEX_PROJECT') or os.getenv('GOOGLE_CLOUD_PROJECT'))}")
print(f"OPENAI_API_KEY loaded: {bool(os.getenv('OPENAI_API_KEY'))}")

Repo root: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory
Loaded q4 module: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/src/openclam/evaluation/q4_earnings_cache.py
VERTEX_PROJECT loaded: True
OPENAI_API_KEY loaded: False

## Configuration

The default universe is the full 55-name Q4 2025 AI/Tech set defined in `q4_earnings_cache.py`.

Set `RUN_AGENT_REFRESH=True` only if you want to regenerate all base agent packets. Set `REFRESH_MARKET_TECHNICAL=True` if you updated the Market/Technical agent and want to refresh that agent plus packets. Set `RUN_CIO=True` to run missing CIO workflows; set `FORCE_RERUN_CIO=True` to overwrite existing CIO workflows.

In [38]:
CACHE_ROOT = REPO_ROOT / q4.DEFAULT_CACHE_ROOT
CACHE_ROOT.mkdir(parents=True, exist_ok=True)

PRE_TRADING_DAYS = 7
POST_TRADING_DAYS = 7
LONG_POST_TRADING_DAYS = 30
NEUTRAL_BAND = 0.02

VERTEX_PROJECT = os.getenv("VERTEX_PROJECT") or os.getenv("GOOGLE_CLOUD_PROJECT")
VERTEX_LOCATION = os.getenv("VERTEX_LOCATION", "us-central1")
VERTEX_MODEL = os.getenv("VERTEX_MODEL", "gemini-2.5-flash")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-nano")
NEWS_MODEL = os.getenv("NEWS_MODEL", "gpt-5.4-nano")
LLM_PROVIDER = "vertex" if VERTEX_PROJECT else "openai"

RUN_AGENT_REFRESH = False
FORCE_RERUN_AGENTS = False
REFRESH_MARKET_TECHNICAL = False
RUN_CIO = False
FORCE_RERUN_CIO = False

# Optional: limit to a subset for quick demos. Keep None for the full 55-name universe.
SELECTED_TICKERS = None

earnings_df = q4.q4_2025_combined_cio_advantage_df(SELECTED_TICKERS)
print("Universe size:", len(earnings_df))
display(earnings_df)

Universe size: 55

,ticker,company,earnings_date,bucket
0,AAPL,Apple,2026-01-29,mega_cap_platform
1,MSFT,Microsoft,2026-01-28,mega_cap_platform
2,GOOGL,Alphabet,2026-02-03,mega_cap_platform
3,AMZN,Amazon,2026-02-05,mega_cap_platform
4,META,Meta Platforms,2026-01-28,mega_cap_platform
5,TSLA,Tesla,2026-01-28,mega_cap_platform
6,NVDA,Nvidia,2026-02-25,mega_cap_platform
7,AMD,Advanced Micro Devices,2026-02-03,ai_semis
8,AVGO,Broadcom,2026-03-05,ai_semis
9,MU,Micron Technology,2025-12-17,ai_semis
10,QCOM,Qualcomm,2026-02-04,ai_semis
11,ARM,Arm Holdings,2026-02-04,ai_semis
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,ai_semis
13,ASML,ASML Holding,2026-01-28,ai_semis
14,AMAT,Applied Materials,2026-02-12,ai_semis
15,LRCX,Lam Research,2026-01-28,ai_semis
16,KLAC,KLA,2026-01-29,ai_semis
17,ORCL,Oracle,2026-03-10,ai_infrastructure
18,DELL,Dell Technologies,2026-02-26,ai_infrastructure
19,SMCI,Super Micro Computer,2026-02-03,ai_infrastructure
20,ANET,Arista Networks,2026-02-17,ai_infrastructure
21,VRT,Vertiv,2026-02-18,ai_infrastructure
22,CRM,Salesforce,2026-02-25,software_cloud
23,ADBE,Adobe,2026-03-11,software_cloud
24,NOW,ServiceNow,2026-01-28,software_cloud
25,SNOW,Snowflake,2026-02-25,software_cloud
26,PLTR,Palantir,2026-02-03,software_cloud
27,DDOG,Datadog,2026-02-12,software_cloud
28,MDB,MongoDB,2026-03-04,software_cloud
29,NET,Cloudflare,2026-02-12,software_cloud
30,MRVL,Marvell Technology,2026-03-05,ai_semis
31,WDC,Western Digital,2026-01-29,ai_semis
32,STX,Seagate Technology,2026-01-21,ai_semis
33,COHR,Coherent,2026-02-05,ai_infrastructure
34,ALAB,Astera Labs,2026-02-10,ai_infrastructure
35,ETN,Eaton,2026-01-30,power_infrastructure
36,PWR,Quanta Services,2026-02-19,power_infrastructure
37,CEG,Constellation Energy,2026-02-19,power_infrastructure
38,NRG,NRG Energy,2026-02-27,power_infrastructure
39,GEV,GE Vernova,2026-01-22,power_infrastructure
40,EQIX,Equinix,2026-02-11,data_center_reit
41,DLR,Digital Realty,2026-02-12,data_center_reit
42,IRM,Iron Mountain,2026-02-20,data_center_reit
43,AMT,American Tower,2026-02-25,data_center_reit
44,CORZ,Core Scientific,2026-03-12,data_center_operator
45,IREN,IREN,2026-02-12,data_center_operator
46,CLS,Celestica,2026-01-27,ai_infrastructure
47,FLEX,Flex,2026-01-28,ai_infrastructure
48,TEAM,Atlassian,2026-01-29,software_cloud
49,ZS,Zscaler,2026-03-04,software_cloud
50,CRWD,CrowdStrike,2026-03-04,software_cloud
51,PANW,Palo Alto Networks,2026-02-12,software_cloud
52,OKTA,Okta,2026-03-03,software_cloud
53,APP,AppLovin,2026-02-12,software_cloud
54,SHOP,Shopify,2026-02-11,software_cloud

## Build Price Evaluation Table

Returns are measured after the earnings-date close. Short horizon is 7 trading days; long horizon is 30 trading days; abnormal returns are measured versus QQQ.

In [39]:
summary_df, paths_df = q4.build_price_tables(
    earnings_df=earnings_df,
    cache_root=CACHE_ROOT,
    pre_trading_days=PRE_TRADING_DAYS,
    post_trading_days=POST_TRADING_DAYS,
    long_post_trading_days=LONG_POST_TRADING_DAYS,
)

print("Price summary rows:", len(summary_df))
news_macro_agent.format_return_columns(summary_df)

Price summary rows: 55

,ticker,company,earnings_date,pre_7d_return,post_1d_return,post_3d_return,post_7d_return,post_30d_return,full_window_return,full_30d_window_return,...,spy_post_30d_return,abnormal_30d_vs_spy,qqq_post_7d_return,abnormal_vs_qqq,qqq_post_30d_return,abnormal_30d_vs_qqq,realized_direction_vs_qqq,realized_30d_direction_vs_qqq,long_horizon_trading_days,bucket
0,AAPL,Apple,2026-01-29,4.69%,0.46%,4.34%,6.43%,-3.07%,11.42%,1.48%,...,-4.57%,1.51%,-2.40%,8.83%,-5.67%,2.60%,up,up,30,mega_cap_platform
1,MSFT,Microsoft,2026-01-28,4.73%,-9.99%,-12.10%,-16.71%,-16.37%,-12.77%,-12.41%,...,-4.22%,-12.15%,-3.72%,-12.99%,-5.68%,-10.69%,down,down,30,mega_cap_platform
2,GOOGL,Alphabet,2026-02-03,3.59%,-1.96%,-4.96%,-9.04%,-9.36%,-5.77%,-6.11%,...,-4.08%,-5.29%,-2.58%,-6.46%,-3.51%,-5.86%,down,down,30,mega_cap_platform
3,AMZN,Amazon,2026-02-05,-8.99%,-5.55%,-7.06%,-9.67%,-7.78%,-17.79%,-16.07%,...,-4.03%,-3.75%,0.72%,-10.39%,-2.51%,-5.27%,down,down,30,mega_cap_platform
4,META,Meta Platforms,2026-01-28,7.82%,10.40%,5.63%,-1.09%,-4.57%,6.64%,2.89%,...,-4.22%,-0.35%,-3.72%,2.64%,-5.68%,1.11%,up,up,30,mega_cap_platform
5,TSLA,Tesla,2026-01-28,-1.38%,-3.45%,-2.24%,-4.72%,-8.45%,-6.03%,-9.71%,...,-4.22%,-4.23%,-3.72%,-0.99%,-5.68%,-2.77%,down,down,30,mega_cap_platform
6,NVDA,Nvidia,2026-02-25,6.97%,-5.46%,-6.69%,-9.07%,-5.95%,-2.73%,0.61%,...,-1.64%,-4.31%,-2.75%,-6.33%,-0.93%,-5.02%,down,down,30,mega_cap_platform
7,AMD,Advanced Micro Devices,2026-02-03,-6.77%,-17.31%,-13.91%,-14.94%,-17.62%,-20.69%,-23.19%,...,-4.08%,-13.54%,-2.58%,-12.36%,-3.51%,-14.11%,down,down,30,ai_semis
8,AVGO,Broadcom,2026-03-05,2.24%,-0.69%,2.95%,-2.36%,22.42%,-0.18%,25.16%,...,4.52%,17.91%,-1.40%,-0.96%,6.69%,15.73%,down,up,30,ai_semis
9,MU,Micron Technology,2025-12-17,-8.67%,10.21%,22.65%,30.58%,94.21%,19.26%,77.38%,...,3.88%,90.33%,3.54%,27.04%,4.42%,89.79%,up,up,30,ai_semis
10,QCOM,Qualcomm,2026-02-04,-3.64%,-8.46%,-6.69%,-5.50%,-11.26%,-8.94%,-14.49%,...,-3.85%,-7.42%,-0.63%,-4.87%,-2.10%,-9.16%,down,down,30,ai_semis
11,ARM,Arm Holdings,2026-02-04,-8.57%,5.70%,18.79%,19.43%,23.76%,9.20%,13.15%,...,-3.85%,27.60%,-0.63%,20.06%,-2.10%,25.86%,up,up,30,ai_semis
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,4.34%,0.22%,-4.54%,-0.97%,8.04%,3.33%,12.73%,...,-0.85%,8.89%,1.50%,-2.47%,-2.20%,10.24%,down,up,30,ai_semis
13,ASML,ASML Holding,2026-01-28,4.74%,2.27%,1.30%,-0.70%,-4.89%,4.01%,-0.38%,...,-4.22%,-0.67%,-3.72%,3.03%,-5.68%,0.79%,up,up,30,ai_semis
14,AMAT,Applied Materials,2026-02-12,3.05%,8.08%,12.46%,15.23%,2.80%,18.74%,5.94%,...,-6.67%,9.47%,1.20%,14.03%,-6.22%,9.02%,up,up,30,ai_semis
15,LRCX,Lam Research,2026-01-28,7.45%,3.59%,-0.87%,-3.58%,-12.45%,3.61%,-5.93%,...,-4.22%,-8.23%,-3.72%,0.15%,-5.68%,-6.78%,up,down,30,ai_semis
16,KLAC,KLA,2026-01-29,13.36%,-15.24%,-19.54%,-14.52%,-15.68%,-3.10%,-4.42%,...,-4.57%,-11.11%,-2.40%,-12.12%,-5.67%,-10.01%,down,down,30,ai_semis
17,ORCL,Oracle,2026-03-10,2.75%,9.18%,3.82%,4.10%,25.94%,6.96%,29.41%,...,5.31%,20.63%,-2.43%,6.52%,7.93%,18.02%,up,up,30,ai_infrastructure
18,DELL,Dell Technologies,2026-02-26,4.62%,21.93%,19.54%,20.63%,46.40%,26.20%,53.16%,...,-1.16%,47.56%,-0.24%,20.88%,0.43%,45.97%,up,up,30,ai_infrastructure
19,SMCI,Super Micro Computer,2026-02-03,-6.40%,13.78%,15.87%,2.56%,2.29%,-4.01%,-4.26%,...,-4.08%,6.37%,-2.58%,5.14%,-3.51%,5.80%,up,up,30,ai_infrastructure
20,ANET,Arista Networks,2026-02-17,10.81%,-2.13%,-6.87%,-8.65%,-13.89%,1.23%,-4.58%,...,-4.50%,-9.39%,1.32%,-9.97%,-3.89%,-10.00%,down,down,30,ai_infrastructure
21,VRT,Vertiv,2026-02-18,24.35%,-0.06%,0.91%,4.80%,6.67%,30.33%,32.65%,...,-4.26%,10.93%,0.25%,4.55%,-3.42%,10.09%,up,up,30,ai_infrastructure
22,CRM,Salesforce,2026-02-25,1.07%,4.03%,0.63%,5.40%,-10.68%,6.53%,-9.72%,...,-1.64%,-9.03%,-2.75%,8.15%,-0.93%,-9.75%,up,down,30,software_cloud
23,ADBE,Adobe,2026-03-11,4.92%,-1.44%,-7.98%,-9.34%,-12.69%,-4.88%,-8.39%,...,5.04%,-17.72%,-4.22%,-5.12%,7.33%,-20.02%,down,down,30,software_cloud
24,NOW,ServiceNow,2026-01-28,1.81%,-9.94%,-8.96%,-22.28%,-12.85%,-20.87%,-11.26%,...,-4.22%,-8.62%,-3.72%,-18.56%,-5.68%,-7.17%,down,down,30,software_cloud
25,SNOW,Snowflake,2026-02-25,-7.18%,2.28%,0.66%,6.66%,-21.85%,-0.99%,-27.46%,...,-1.64%,-20.21%,-2.75%,9.41%,-0.93%,-20.92%,up,down,30,software_cloud
26,PLTR,Palantir,2026-02-03,-6.91%,-11.62%,-13.92%,-18.21%,-3.24%,-23.86%,-9.92%,...,-4.08%,0.84%,-2.58%,-15.63%,-3.51%,0.27%,down,up,30,software_cloud
27,DDOG,Datadog,2026-02-12,5.41%,-0.74%,-3.45%,-17.20%,-9.24%,-12.73%,-4.33%,...,-6.67%,-2.57%,1.20%,-18.41%,-6.22%,-3.02%,down,down,30,software_cloud
28,MDB,MongoDB,2026-03-04,-18.78%,6.42%,9.57%,5.04%,1.26%,-14.69%,-17.76%,...,2.69%,-1.43%,-2.79%,7.82%,5.00%,-3.74%,up,down,30,software_cloud
29,NET,Cloudflare,2026-02-12,8.73%,5.77%,3.39%,-11.54%,9.64%,-3.82%,19.21%,...,-6.67%,16.31%,1.20%,-12.74%,-6.22%,15.86%,down,up,30,software_cloud
30,MRVL,Marvell Technology,2026-03-05,-3.46%,18.35%,23.28%,21.01%,84.67%,16.83%,78.29%,...,4.52%,80.16%,-1.40%,22.41%,6.69%,77.98%,up,up,30,ai_semis
31,WDC,Western Digital,2026-01-29,24.86%,-10.12%,4.25%,2.72%,-2.15%,28.26%,22.18%,...,-4.57%,2.42%,-2.40%,5.12%,-5.67%,3.52%,up,up,30,ai_semis
32,STX,Seagate Technology,2026-01-21,13.23%,0.67%,4.09%,18.44%,6.72%,34.10%,20.83%,...,-0.60%,7.31%,0.91%,17.53%,-1.20%,7.91%,up,up,30,ai_semis
33,COHR,Coherent,2026-02-05,-2.22%,8.81%,9.14%,5.12%,21.21%,2.79%,18.52%,...,-4.03%,25.24%,0.72%,4.41%,-2.51%,23.72%,up,up,30,ai_infrastructure
34,ALAB,Astera Labs,2026-02-10,21.40%,-21.41%,-29.28%,-29.08%,-34.20%,-13.90%,-20.11%,...,-4.84%,-29.35%,-0.44%,-28.65%,-3.75%,-30.45%,down,down,30,ai_infrastructure
35,ETN,Eaton,2026-01-30,3.98%,2.28%,3.86%,7.41%,3.06%,11.69%,7.16%,...,-3.32%,6.37%,-1.67%,9.09%,-3.46%,6.51%,up,up,30,power_infrastructure
36,PWR,Quanta Services,2026-02-19,7.66%,-0.24%,2.56%,3.37%,1.22%,11.29%,8.97%,...,-3.92%,5.14%,0.77%,2.60%,-2.94%,4.16%,up,up,30,power_infrastructure
37,CEG,Constellation Energy,2026-02-19,7.17%,1.09%,7.19%,12.17%,-6.33%,20.21%,0.38%,...,-3.92%,-2.41%,0.77%,11.41%,-2.94%,-3.39%,up,down,30,power_infrastructure
38,NRG,NRG Energy,2026-02-27,4.62%,-1.89%,-8.62%,-13.30%,-4.87%,-9.30%,-0.48%,...,0.29%,-5.16%,0.08%,-13.38%,1.79%,-6.66%,down,down,30,power_infrastructure
39,GEV,GE Vernova,2026-01-22,3.42%,-0.59%,4.69%,14.10%,19.28%,18.01%,23.36%,...,-2.41%,21.69%,0.87%,13.23%,-3.38%,22.66%,up,up,30,power_infrastructure
40,EQIX,Equinix,2026-02-11,7.05%,10.41%,9.73%,9.00%,11.66%,16.69%,19.53%,...,-6.52%,18.18%,-1.91%,10.91%,-6.30%,17.95%,up,up,30,data_center_reit
41,DLR,Digital Realty,2026-02-12,9.64%,0.37%,-2.38%,-1.15%,-2.05%,8.39%,7.40%,...,-6.67%,4.62%,1.20%,-2.35%,-6.22%,4.17%,down,up,30,data_center_reit
42,IRM,Iron Mountain,2026-02-20,11.06%,0.82%,1.35%,-2.28%,-4.61%,8.53%,5.94%,...,-4.16%,-0.44%,-1.19%,-1.09%,-3.21%,-1.39%,down,down,30,data_center_reit
43,AMT,American Tower,2026-02-25,-5.01%,1.39%,4.23%,3.35%,-1.40%,-1.83%,-6.34%,...,-1.64%,0.24%,-2.75%,6.09%,-0.93%,-0.47%,up,down,30,data_center_reit
44,CORZ,Core Scientific,2026-03-12,6.14%,1.54%,1.11%,2.09%,28.57%,8.37%,36.47%,...,7.48%,21.09%,-1.43%,3.52%,11.29%,17.28%,up,up,30,data_center_operator
45,IREN,IREN,2026-02-12,-26.40%,5.47%,5.12%,13.54%,-12.34%,-16.44%,-35.48%,...,-6.67%,-5.67%,1.20%,12.34%,-6.22%,-6.12%,up,down,30,data_center_operator
46,CLS,Celestica,2026-01-27,6.26%,3.62%,-15.66%,-11.49%,-20.22%,-5.95%,-15.22%,...,-2.75%,-17.47%,-5.40%,-6.09%,-3.71%,-16.51%,down,down,30,ai_infrastructure
47,FLEX,Flex,2026-01-28,2.22%,-1.21%,-2.40%,-3.46%,-4.48%,-1.31%,-2.36%,...,-4.22%,-0.26%,-3.72%,0.27%,-5.68%,1.20%,up,up,30,ai_infrastructure
48,TEAM,Atlassian,2026-01-29,1.97%,-1.83%,-12.78%,-24.21%,-37.52%,-22.73%,-36.30%,...,-4.57%,-32.95%,-2.40%,-21.81%,-5.67%,-31.85%,down,down,30,software_cloud
49,ZS,Zscaler,2026-03-04,9.02%,3.68%,4.10%,-1.57%,-14.01%,7.31%,-6.25%,...,2.69%,-16.70%,-2.79%,1.22%,5.00%,-19.01%,up,down,30,software_cloud
50,CRWD,CrowdStrike,2026-03-04,16.37%,4.53%,6.49%,8.36%,2.58%,26.10%,19.37%,...,2.69%,-0.11%,-2.79%,11.15%,5.00%,-2.42%,up,down,30,software_cloud
51,PANW,Palo Alto Networks,2026-02-12,-2.06%,2.54%,-6.42%,-12.98%,-9.70%,-14.78%,-11.56%,...,-6.67%,-3.03%,1.20%,-14.19%,-6.22%,-3.48%,down,down,30,software_cloud
52,OKTA,Okta,2026-03-03,-2.38%,-1.08%,11.31%,8.87%,-7.13%,6.27%,-9.34%,...,3.16%,-10.29%,-0.72%,9.58%,6.09%,-13.22%,up,down,30,software_cloud
53,APP,AppLovin,2026-02-12,-20.55%,6.44%,10.22%,7.17%,3.89%,-14.85%,-17.45%,...,-6.67%,10.57%,1.20%,5.97%,-6.22%,10.11%,up,up,30,software_cloud
54,SHOP,Shopify,2026-02-11,-10.20%,-6.78%,-4.36%,-1.20%,-2.76%,-11.29%,-12.69%,...,-6.52%,3.76%,-1.91%,0.70%,-6.30%,3.53%,up,up,30,software_cloud

## Load or Refresh Agent Packets

This cell loads cached packets by default. If you changed agent code, turn on the relevant refresh flag in the configuration cell.

In [40]:
if RUN_AGENT_REFRESH:
    packets_by_ticker, errors_by_ticker = q4.run_q4_2025_universe_agents(
        earnings_df=earnings_df,
        cache_root=CACHE_ROOT,
        force=FORCE_RERUN_AGENTS,
        lookback_days=14,
        max_news=10,
        llm_provider=LLM_PROVIDER,
        vertex_project=VERTEX_PROJECT,
        vertex_location=VERTEX_LOCATION,
        vertex_model=VERTEX_MODEL,
        openai_model=OPENAI_MODEL,
        news_model=NEWS_MODEL,
    )
elif REFRESH_MARKET_TECHNICAL:
    packets_by_ticker = q4.rerun_cached_market_technical_agent(
        earnings_df,
        cache_root=CACHE_ROOT,
        vertex_project=VERTEX_PROJECT,
        vertex_location=VERTEX_LOCATION,
        vertex_model=VERTEX_MODEL,
        openai_model=OPENAI_MODEL,
    )
    errors_by_ticker = {}
else:
    packets_by_ticker = q4.load_cached_packets_by_ticker(CACHE_ROOT)
    errors_by_ticker = {}

expected_tickers = set(summary_df["ticker"].str.upper())
available_tickers = set(packets_by_ticker)
print("Expected tickers:", len(expected_tickers))
print("Cached packet tickers:", len(available_tickers & expected_tickers))
print("Missing packet tickers:", sorted(expected_tickers - available_tickers))
errors_by_ticker

Expected tickers: 55
Cached packet tickers: 55
Missing packet tickers: []

{}

## CIO Workflows

This cell runs CIO workflows incrementally only when requested, then always rebuilds `cio_eval` from cached per-ticker CIO JSON files. Incremental saving means interrupted runs keep completed tickers.

In [42]:
cio_dir = CACHE_ROOT / "cio"
cio_dir.mkdir(parents=True, exist_ok=True)
expected_tickers = list(summary_df["ticker"].str.upper())
cached_cio_tickers = {path.stem.upper() for path in cio_dir.glob("*.json")}
missing_cio_tickers = [ticker for ticker in expected_tickers if ticker not in cached_cio_tickers]

if FORCE_RERUN_CIO:
    tickers_to_run = expected_tickers
elif RUN_CIO:
    tickers_to_run = missing_cio_tickers
else:
    tickers_to_run = []

print("Expected CIO tickers:", len(expected_tickers))
print("Cached CIO tickers:", len(cached_cio_tickers & set(expected_tickers)))
print("Missing CIO tickers:", missing_cio_tickers)
print("Tickers selected for CIO run:", tickers_to_run)

incremental_cio_evals = []
incremental_cio_results = {}

for ticker in tickers_to_run:
    print("" + "=" * 80)
    print(f"Running CIO for {ticker}...")
    print("=" * 80)

    one_summary_df = summary_df[summary_df["ticker"].str.upper() == ticker].copy()
    one_packets = {ticker: packets_by_ticker.get(ticker, [])}

    if not one_packets[ticker]:
        print(f"Skipped {ticker}: no packets found.")
        continue

    try:
        one_cio_eval, one_cio_results, _ = q4.run_cached_cio_eval(
            one_summary_df,
            one_packets,
            cache_root=CACHE_ROOT,
            long_post_trading_days=LONG_POST_TRADING_DAYS,
            neutral_band=NEUTRAL_BAND,
            use_llm_debate=True,
            use_llm_decision=True,
            llm_provider=LLM_PROVIDER,
            debate_model=VERTEX_MODEL if VERTEX_PROJECT else OPENAI_MODEL,
            decision_model=VERTEX_MODEL if VERTEX_PROJECT else OPENAI_MODEL,
            vertex_project=VERTEX_PROJECT,
            vertex_location=VERTEX_LOCATION,
        )
        incremental_cio_evals.append(one_cio_eval)
        incremental_cio_results[ticker] = one_cio_results.get(ticker)
        print(f"Saved CIO result for {ticker}: {cio_dir / f'{ticker}.json'}")
    except Exception as exc:
        print(f"Failed CIO for {ticker}: {repr(exc)}")

cio_eval, cio_results, cio_summary = q4.rebuild_cio_eval_from_cache(
    summary_df,
    cache_root=CACHE_ROOT,
    long_post_trading_days=LONG_POST_TRADING_DAYS,
    neutral_band=NEUTRAL_BAND,
    output_name="cio_eval_full_55" if len(summary_df) >= 50 else "cio_eval_selected",
)

print(cio_summary)
news_macro_agent.format_return_columns(cio_eval)

Expected CIO tickers: 55
Cached CIO tickers: 55
Missing CIO tickers: []
Tickers selected for CIO run: []
{'overall': {'cases': 55, 'cio_ready_cases': 55, 'debate_trigger_rate': 0.509090909090909, 'cio_short_direction_match_evaluable': 55, 'cio_short_direction_match_matched': 23, 'cio_short_direction_match_accuracy': 0.41818181818181815, 'cio_long_direction_match_evaluable': 55, 'cio_long_direction_match_matched': 30, 'cio_long_direction_match_accuracy': 0.5454545454545454}, 'by_bucket': {'ai_infrastructure': {'cases': 9, 'debate_trigger_rate': 0.5555555555555556, 'short_accuracy': 0.5555555555555556, 'long_accuracy': 0.5555555555555556, 'avg_confidence': 0.7833333333333333}, 'ai_semis': {'cases': 13, 'debate_trigger_rate': 0.3076923076923077, 'short_accuracy': 0.5384615384615384, 'long_accuracy': 0.6153846153846154, 'avg_confidence': 0.8148461538461539}, 'data_center_operator': {'cases': 2, 'debate_trigger_rate': 0.5, 'short_accuracy': 0.0, 'long_accuracy': 0.5, 'avg_confidence': 0.575}, 'data_center_reit': {'cases': 4, 'debate_trigger_rate': 0.5, 'short_accuracy': 0.25, 'long_accuracy': 0.75, 'avg_confidence': 0.7625}, 'mega_cap_platform': {'cases': 7, 'debate_trigger_rate': 0.7142857142857143, 'short_accuracy': 0.7142857142857143, 'long_accuracy': 0.2857142857142857, 'avg_confidence': 0.7785714285714286}, 'power_infrastructure': {'cases': 5, 'debate_trigger_rate': 0.4, 'short_accuracy': 0.0, 'long_accuracy': 0.6, 'avg_confidence': 0.7448}, 'software_cloud': {'cases': 15, 'debate_trigger_rate': 0.6, 'short_accuracy': 0.3333333333333333, 'long_accuracy': 0.5333333333333333, 'avg_confidence': 0.7604666666666665}}}

,ticker,company,earnings_date,pre_7d_return,post_1d_return,post_3d_return,post_7d_return,post_30d_return,full_window_return,full_30d_window_return,...,cio_confidence,cio_debate_triggered,cio_debate_conflict_level,cio_routing_bucket,cio_routing_rationale,cio_reason,cio_short_direction_match,cio_short_direction_match_reason,cio_long_direction_match,cio_long_direction_match_reason
0,AAPL,Apple,2026-01-29,4.69%,0.46%,4.34%,6.43%,-3.07%,11.42%,1.48%,...,0.850,True,high,None,None,The committee reached a unanimous Bullish shor...,True,matched,False,neutral missed: abnormal return moved outside ...
1,MSFT,Microsoft,2026-01-28,4.73%,-9.99%,-12.10%,-16.71%,-16.37%,-12.77%,-12.41%,...,0.750,False,low,None,None,The decision aligns with the deterministic gua...,True,matched,False,missed
2,GOOGL,Alphabet,2026-02-03,3.59%,-1.96%,-4.96%,-9.04%,-9.36%,-5.77%,-6.11%,...,0.700,False,low,None,None,The final decision is to adopt a Bearish short...,True,matched,False,missed
3,AMZN,Amazon,2026-02-05,-8.99%,-5.55%,-7.06%,-9.67%,-7.78%,-17.79%,-16.07%,...,0.850,True,high,None,None,The committee reached a high-conviction consen...,True,matched,False,missed
4,META,Meta Platforms,2026-01-28,7.82%,10.40%,5.63%,-1.09%,-4.57%,6.64%,2.89%,...,0.800,True,high,None,None,The final decision is an override of the initi...,False,missed,True,matched
5,TSLA,Tesla,2026-01-28,-1.38%,-3.45%,-2.24%,-4.72%,-8.45%,-6.03%,-9.71%,...,0.850,True,high,None,None,The decision is driven by the unanimous post-d...,True,matched,True,matched
6,NVDA,Nvidia,2026-02-25,6.97%,-5.46%,-6.69%,-9.07%,-5.95%,-2.73%,0.61%,...,0.650,True,high,None,None,CIO Override: I am overriding the deterministi...,False,missed,False,neutral missed: abnormal return moved outside ...
7,AMD,Advanced Micro Devices,2026-02-03,-6.77%,-17.31%,-13.91%,-14.94%,-17.62%,-20.69%,-23.19%,...,0.850,True,high,None,None,I am overriding the deterministic guardrail's ...,True,matched,False,missed
8,AVGO,Broadcom,2026-03-05,2.24%,-0.69%,2.95%,-2.36%,22.42%,-0.18%,25.16%,...,0.800,False,low,None,None,The committee is overriding the guardrail's 'S...,False,missed,True,matched
9,MU,Micron Technology,2025-12-17,-8.67%,10.21%,22.65%,30.58%,94.21%,19.26%,77.38%,...,0.872,False,low,None,None,The committee reached a high-conviction bullis...,True,matched,True,matched
10,QCOM,Qualcomm,2026-02-04,-3.64%,-8.46%,-6.69%,-5.50%,-11.26%,-8.94%,-14.49%,...,0.800,False,low,ai_semis,AI semiconductor moves depend on technical con...,The committee is in strong agreement on a shor...,True,matched,False,neutral missed: abnormal return moved outside ...
11,ARM,Arm Holdings,2026-02-04,-8.57%,5.70%,18.79%,19.43%,23.76%,9.20%,13.15%,...,0.749,True,high,ai_semis,AI semiconductor moves depend on technical con...,A unanimous post-debate consensus among all ag...,False,missed,False,neutral missed: abnormal return moved outside ...
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,4.34%,0.22%,-4.54%,-0.97%,8.04%,3.33%,12.73%,...,0.872,False,low,None,None,The committee's final decision is a high-confi...,False,missed,True,matched
13,ASML,ASML Holding,2026-01-28,4.74%,2.27%,1.30%,-0.70%,-4.89%,4.01%,-0.38%,...,0.650,False,low,None,None,The committee reached a consensus on a short-t...,False,missed,True,neutral matched: abnormal return stayed inside...
14,AMAT,Applied Materials,2026-02-12,3.05%,8.08%,12.46%,15.23%,2.80%,18.74%,5.94%,...,0.700,False,low,ai_semis,AI semiconductor moves depend on technical con...,The committee's final decision is to adopt a B...,True,matched,True,matched
15,LRCX,Lam Research,2026-01-28,7.45%,3.59%,-0.87%,-3.58%,-12.45%,3.61%,-5.93%,...,0.900,False,low,ai_semis,AI semiconductor moves depend on technical con...,The committee's final decision is a high-convi...,True,matched,False,missed
16,KLAC,KLA,2026-01-29,13.36%,-15.24%,-19.54%,-14.52%,-15.68%,-3.10%,-4.42%,...,0.900,True,high,ai_semis,AI semiconductor moves depend on technical con...,The final decision aligns with the unanimous p...,True,matched,False,neutral missed: abnormal return moved outside ...
17,ORCL,Oracle,2026-03-10,2.75%,9.18%,3.82%,4.10%,25.94%,6.96%,29.41%,...,0.750,False,low,None,None,I am overriding the deterministic guardrail's ...,False,neutral missed: abnormal return moved outside ...,True,matched
18,DELL,Dell Technologies,2026-02-26,4.62%,21.93%,19.54%,20.63%,46.40%,26.20%,53.16%,...,0.850,False,low,None,None,The committee's final decision is Bullish on b...,True,matched,True,matched
19,SMCI,Super Micro Computer,2026-02-03,-6.40%,13.78%,15.87%,2.56%,2.29%,-4.01%,-4.26%,...,0.850,True,high,ai_infrastructure,AI infrastructure is driven by second-order de...,I am overriding the guardrail's 'Bullish' long...,True,matched,False,neutral missed: abnormal return moved outside ...
20,ANET,Arista Networks,2026-02-17,10.81%,-2.13%,-6.87%,-8.65%,-13.89%,1.23%,-4.58%,...,0.800,False,low,None,None,The committee unanimously agrees on the long-t...,False,neutral missed: abnormal return moved outside ...,False,missed
21,VRT,Vertiv,2026-02-18,24.35%,-0.06%,0.91%,4.80%,6.67%,30.33%,32.65%,...,0.800,True,high,None,None,The committee reached a unanimous and high-con...,False,neutral missed: abnormal return moved outside ...,True,matched
22,CRM,Salesforce,2026-02-25,1.07%,4.03%,0.63%,5.40%,-10.68%,6.53%,-9.72%,...,0.557,False,low,None,None,The committee's decision is an override of the...,False,missed,False,neutral missed: abnormal return moved outside ...
23,ADBE,Adobe,2026-03-11,4.92%,-1.44%,-7.98%,-9.34%,-12.69%,-4.88%,-8.39%,...,0.600,False,low,software_cloud,Software/cloud reactions are often driven by g...,I am overriding the guardrail's 'Bearish' shor...,False,neutral missed: abnormal return moved outside ...,True,matched
24,NOW,ServiceNow,2026-01-28,1.81%,-9.94%,-8.96%,-22.28%,-12.85%,-20.87%,-11.26%,...,0.800,True,high,software_cloud,Software/cloud reactions are often driven by g...,The committee reached a strong post-debate con...,True,matched,False,missed
25,SNOW,Snowflake,2026-02-25,-7.18%,2.28%,0.66%,6.66%,-21.85%,-0.99%,-27.46%,...,0.900,True,high,software_cloud,Software/cloud reactions are often driven by g...,The decision is an override of the determinist...,False,missed,False,neutral missed: abnormal return moved outside ...
26,PLTR,Palantir,2026-02-03,-6.91%,-11.62%,-13.92%,-18.21%,-3.24%,-23.86%,-9.92%,...,0.700,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am concurring with the deterministic guardra...,True,matched,True,matched
27,DDOG,Datadog,2026-02-12,5.41%,-0.74%,-3.45%,-17.20%,-9.24%,-12.73%,-4.33%,...,0.600,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am overriding the guardrail's short-term 'Bu...,False,neutral missed: abnormal return moved outside ...,False,neutral missed: abnormal return moved outside ...
28,MDB,MongoDB,2026-03-04,-18.78%,6.42%,9.57%,5.04%,1.26%,-14.69%,-17.76%,...,0.900,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am confirming the deterministic guardrail's ...,False,missed,True,matched
29,NET,Cloudflare,2026-02-12,8.73%,5.77%,3.39%,-11.54%,9.64%,-3.82%,19.21%,...,0.600,False,low,software_cloud,Software/cloud reactions are often driven by g...,The committee is in consensus on a short-term ...,False,missed,False,neutral missed: abnormal return moved outside ...
30,MRVL,Marvell Technology,2026-03-05,-3.46%,18.35%,23.28%,21.01%,84.67%,16.83%,78.29%,...,0.850,False,low,ai_semis,AI semiconductor moves depend on technical con...,I am overriding the Neutral long-term stances ...,True,matched,True,matched
31,WDC,Western Digital,2026-01-29,24.86%,-10.12%,4.25%,2.72%,-2.15%,28.26%,22.18%,...,0.800,False,low,ai_semis,AI semiconductor moves depend on technical con...,The committee reached a strong consensus. All ...,False,missed,True,matched
32,STX,Seagate Technology,2026-01-21,13.23%,0.67%,4.09%,18.44%,6.72%,34.10%,20.83%,...,0.850,True,high,ai_semis,AI semiconductor moves depend on technical con...,This decision reflects the powerful post-debat...,False,neutral missed: abnormal return moved outside ...,True,matched
33,COHR,Coherent,2026-02-05,-2.22%,8.81%,9.14%,5.12%,21.21%,2.79%,18.52%,...,0.800,True,high,ai_infrastructure,AI infrastructure is driven by second-order de...,I am overriding the guardrail's low confidence...,True,matched,True,matched
34,ALAB,Astera Labs,2026-02-10,21.40%,-21.41%,-29.28%,-29.08%,-34.20%,-13.90%,-20.11%,...,0.800,True,high,ai_infrastructure,AI infrastructure is driven by second-order de...,I am overriding the deterministic guardrail's ...,True,matched,False,neutral missed: abnormal return moved outside ...
35,ETN,Eaton,2026-01-30,3.98%,2.28%,3.86%,7.41%,3.06%,11.69%,7.16%,...,0.800,True,high,None,None,I am overriding the deterministic guardrail's ...,False,missed,True,matched
36,PWR,Quanta Services,2026-02-19,7.66%,-0.24%,2.56%,3.37%,1.22%,11.29%,8.97%,...,0.724,False,low,power_infrastructure,Power infrastructure is a thematic second-orde...,The final decision is to override the determin...,False,neutral missed: abnormal return moved outside ...,True,matched
37,CEG,Constellation Energy,2026-02-19,7.17%,1.09%,7.19%,12.17%,-6.33%,20.21%,0.38%,...,0.800,True,high,None,None,The committee's decision aligns with the deter...,False,missed,False,missed
38,NRG,NRG Energy,2026-02-27,4.62%,-1.89%,-8.62%,-13.30%,-4.87%,-9.30%,-0.48%,...,0.700,False,low,power_infrastructure,Power infrastructure is a thematic second-orde...,I am overriding the guardrail's short-term 'Bu...,False,neutral missed: abnormal return moved outside ...,False,missed
39,GEV,GE Vernova,2026-01-22,3.42%,-0.59%,4.69%,14.10%,19.28%,18.01%,23.36%,...,0.700,False,low,power_infrastructure,Power infrastructure is a thematic second-orde...,I am overriding the guardrail's short-term 'Be...,False,neutral missed: abnormal return moved outside ...,True,matched
40,EQIX,Equinix,2026-02-11,7.05%,10.41%,9.73%,9.00%,11.66%,16.69%,19.53%,...,0.800,False,low,None,None,I am overriding the deterministic guardrail's ...,False,neutral missed: abnormal return moved outside ...,True,matched
41,DLR,Digital Realty,2026-02-12,9.64%,0.37%,-2.38%,-1.15%,-2.05%,8.39%,7.40%,...,0.700,False,low,data_center_reit,Data-center REITs require balancing capital-co...,The committee is in strong agreement on the lo...,False,neutral missed: abnormal return moved outside ...,True,matched
42,IRM,Iron Mountain,2026-02-20,11.06%,0.82%,1.35%,-2.28%,-4.61%,8.53%,5.94%,...,0.800,True,high,data_center_reit,Data-center REITs require balancing capital-co...,I am overriding the guardrail's low confidence...,True,neutral matched: abnormal return stayed inside...,False,missed
43,AMT,American Tower,2026-02-25,-5.01%,1.39%,4.23%,3.35%,-1.40%,-1.83%,-6.34%,...,0.750,True,high,data_center_reit,Data-center REITs require balancing capital-co...,I am overriding the low confidence score of th...,False,missed,True,neutral matched: abnormal return stayed inside...
44,CORZ,Core Scientific,2026-03-12,6.14%,1.54%,1.11%,2.09%,28.57%,8.37%,36.47%,...,0.500,False,low,data_center_operator,Data-center operators are high-beta event trad...,I am overriding the deterministic guardrail's ...,False,neutral missed: abnormal return moved outside ...,True,matched
45,IREN,IREN,2026-02-12,-26.40%,5.47%,5.12%,13.54%,-12.34%,-16.44%,-35.48%,...,0.650,True,high,data_center_operator,Data-center operators are high-beta event trad...,I am overriding the deterministic guardrail's ...,False,neutral missed: abnormal return moved outside ...,False,missed
46,CLS,Celestica,2026-01-27,6.26%,3.62%,-15.66%,-11.49%,-20.22%,-5.95%,-15.22%,...,0.800,True,high,ai_infrastructure,AI infrastructure is driven by second-order de...,The final decision is an override of the deter...,False,missed,False,missed
47,FLEX,Flex,2026-01-28,2.22%,-1.21%,-2.40%,-3.46%,-4.48%,-1.31%,-2.36%,...,0.600,False,low,ai_infrastructure,AI infrastructure is driven by second-order de...,The committee is constructive on Flex's long-t...,True,neutral matched: abnormal return stayed inside...,True,matched
48,TEAM,Atlassian,2026-01-29,1.97%,-1.83%,-12.78%,-24.21%,-37.52%,-22.73%,-36.30%,...,0.800,False,low,software_cloud,Software/cloud reactions are often driven by g...,The final decision is to adopt a Bearish stanc...,True,matched,True,matched
49,ZS,Zscaler,2026-03-04,9.02%,3.68%,4.10%,-1.57%,-14.01%,7.31%,-6.25%,...,0.800,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am upholding the deterministic guardrail's B...,False,missed,True,matched
50,CRWD,CrowdStrike,2026-03-04,16.37%,4.53%,6.49%,8.36%,2.58%,26.10%,19.37%,...,0.850,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am overriding the guardrail's low confidence...,True,matched,False,missed
51,PANW,Palo Alto Networks,2026-02-12,-2.06%,2.54%,-6.42%,-12.98%,-9.70%,-14.78%,-11.56%,...,0.700,False,low,software_cloud,Software/cloud reactions are often driven by g...,The committee's decision is to adopt a Bearish...,True,matched,True,matched
52,OKTA,Okta,2026-03-03,-2.38%,-1.08%,11.31%,8.87%,-7.13%,6.27%,-9.34%,...,0.900,True,high,software_cloud,Software/cloud reactions are often driven by g...,This decision overrides the guardrail's 'Small...,False,missed,True,matched
53,APP,AppLovin,2026-02-12,-20.55%,6.44%,10.22%,7.17%,3.89%,-14.85%,-17.45%,...,0.850,True,high,software_cloud,Software/cloud reactions are often driven by g...,I am overriding the deterministic guardrail's ...,False,missed,True,matched
54,SHOP,Shopify,2026-02-11,-10.20%,-6.78%,-4.36%,-1.20%,-2.76%,-11.29%,-12.69%,...,0.850,False,low,software_cloud,Software/cloud reactions are often driven by g...,The final decision aligns with the determinist...,False,missed,False,missed

## Optional CIO Inspection

Use this cell to inspect one ticker's saved agent packets and debate trace.

In [43]:
INSPECT_TICKER = "NVDA"

cached = q4.load_cached_ticker(INSPECT_TICKER, CACHE_ROOT)
print("Saved files:")
for key, value in q4.cached_ticker_paths(INSPECT_TICKER, CACHE_ROOT).items():
    print(key, value)

workflow = cio_results.get(INSPECT_TICKER) or q4.load_json(CACHE_ROOT / "cio" / f"{INSPECT_TICKER}.json")
agent_summary = pd.DataFrame(workflow["synthesis"].get("agent_view_summary", []))
debate_summary = pd.DataFrame(workflow["debate"].get("debate_responses", []))

display(Markdown(f"### {INSPECT_TICKER} Agent View Summary"))
display(agent_summary)

display(Markdown(f"### {INSPECT_TICKER} Debate Responses"))
display(debate_summary)

display(Markdown(f"### {INSPECT_TICKER} Final CIO Decision"))
display(workflow["final_decision"])

Saved files:
news_macro /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/news_macro/NVDA.json
market_technical /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/market_technical/NVDA.json
fundamental /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/fundamental/NVDA.json
packets /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/packets/NVDA.json
cio /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/NVDA.json
context /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/contexts/NVDA.json
errors /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/errors/NVDA.json

### NVDA Agent View Summary

,agent_name,short_term_stance,long_term_stance,confidence,rationale
0,news_macro,Bullish,Bearish,0.65,The short-term stance is Bullish due to a dire...
1,fundamental,Neutral,Bullish,0.60,NVIDIA reported an exceptionally strong quarte...
2,market_technical,Neutral,Bullish,0.70,The primary tension is between the established...

### NVDA Debate Responses

,response_type,agreement,disagreement,revised_short_term_stance,revised_long_term_stance,revised_confidence,revision_rationale,evidence_needed
0,revision,{'fundamental': 'The fundamental agent's data ...,{'fundamental': 'I disagree with the fundament...,Neutral,Bearish,0.60,I am revising my short-term stance from 'Bulli...,[Future earnings reports from AMD to quantify ...
1,revision,{'news_macro': 'I agree with the news_macro ag...,{'news_macro': 'I disagree with the news_macro...,Bullish,Bullish,0.80,My original Neutral short-term stance and mode...,[Quantification of the financial impact of the...
2,revision,[I agree with the news_macro agent that the re...,[I assign a lower weight to the news_macro age...,Bullish,Bullish,0.85,NaN,[The official earnings release detailing speci...

### NVDA Final CIO Decision

{'ticker': 'NVDA',
 'company': 'Nvidia',
 'final_short_term_stance': 'Bullish',
 'final_long_term_stance': 'Neutral',
 'investment_action': 'Hold / Monitor',
 'position_size_hint': 'Small',
 'confidence': 0.65,
 'core_thesis': "The short-term outlook is bullish, driven by an exceptional earnings and guidance beat that should act as a catalyst to resolve the recent price consolidation to the upside. However, the long-term view is downgraded to neutral due to a significant conflict between stellar current fundamentals and mounting, unpriced, forward-looking risks. While Nvidia's dominance is undeniable today, credible threats from competition (e.g., AMD's win with Meta) and geopolitical supply chain risks (TSM dependency) create significant uncertainty about the sustainability of its current market share and valuation premium.",
 'why_now': "The immediate catalyst is the forecast-beating earnings report, which has temporarily allayed fears of an AI slowdown. The stock's recent consolidation, coupled with this strong fundamental news, presents a tactical opportunity for short-term upside. The long-term view warrants monitoring how the competitive and geopolitical risks evolve before committing new long-term capital.",
 'key_supporting_evidence': ['Exceptional quarter-over-quarter growth confirmed by the fundamental agent: Revenue +19.5%, Net Income +34.6%, and Free Cash Flow +57.8%.',
  'Strong earnings and guidance beat expectations, as reported by the news_macro agent, providing a clear positive catalyst.',
  'The technical picture shows a stock in a healthy consolidation (8.37% drawdown) within a strong, intact long-term uptrend, poised to react to the earnings news.',
  'The news_macro agent provided evidence of the primary long-term risk materializing: AMD securing a major deal with Meta, signaling the beginning of serious customer diversification away from Nvidia.',
  "Persistent geopolitical risk related to TSM and Taiwan, which represents a significant, unpriced tail risk to Nvidia's supply chain."],
 'key_risks': ["Competition: The primary risk is that major customers (hyperscalers) accelerate their shift to dual-sourcing (AMD) or in-house custom silicon, eroding Nvidia's market share and pricing power faster than the market anticipates.",
  "Geopolitics: A conflict or major disruption involving Taiwan would severely impact Nvidia's supply chain via its dependency on TSM, a risk the market has largely ignored to date.",
  "Valuation: The stock's premium valuation (Trailing P/E of 40.5x) is predicated on sustained hyper-growth, making it highly vulnerable to any signs of deceleration or margin pressure.",
  'Market Saturation: The current rate of growth is historically unprecedented and may not be sustainable as the initial wave of AI infrastructure build-out matures.'],
 'agent_view_summary': [{'agent_name': 'news_macro',
   'short_term_stance': 'Bullish',
   'long_term_stance': 'Bearish',
   'confidence': 0.65,
   'rationale': "The short-term stance is Bullish due to a direct earnings and guidance beat that exceeded high expectations, likely driving a relief rally and outperformance. The long-term stance is Bearish because mounting evidence from related-company news (AMD's Meta win, TSM geopolitical risk, China's tech decoupling) points to future market share loss, margin pressure, and a higher risk premium, making continued outperformance versus the QQQ challenging."},
  {'agent_name': 'fundamental',
   'short_term_stance': 'Neutral',
   'long_term_stance': 'Bullish',
   'confidence': 0.6,
   'rationale': "NVIDIA reported an exceptionally strong quarter with significant sequential growth across all key metrics, including revenue, net income, and free cash flow. The company's profitability is extremely high, and its fundamentals are rapidly strengthening, supporting a bullish outlook despite a premium valuation."},
  {'agent_name': 'market_technical',
   'short_term_stance': 'Neutral',
   'long_term_stance': 'Bullish',
   'confidence': 0.7,
   'rationale': 'The primary tension is between the established bullish trend and a clear loss of short-term momentum. The bearish MACD crossover is the most critical signal, suggesting the recent uptrend has paused, warranting caution until momentum reasserts itself.'}],
 'debate_summary': {'debate_triggered': True,
  'conflict_level': 'high',
  'debate_reason': ['Long-term views contain both bullish and bearish calls.'],
  'debate_responses': [{'response_type': 'revision',
    'agreement': {'fundamental': "The fundamental agent's data provides quantitative validation for my news-based assessment of a 'strong earnings beat'. Specifically, the exceptional sequential growth in revenue (+19.5%), net income (+34.6%), and free cash flow (+57.8%) confirms the underlying strength that drove the positive news cycle.",
     'market_technical': "The market_technical agent's short-term signals, particularly the 'Bearish Momentum Shift' (MACD crossover) and 'Correction in Progress' (8.37% drawdown), align with a 'sell-the-news' or consolidation phase after the earnings event. This provides crucial context for the market's current price action, suggesting the initial bullish impulse from the news has been absorbed."},
    'disagreement': {'fundamental': "I disagree with the fundamental agent's long-term 'Bullish' stance. It is based on extrapolating incredibly strong, but historical, financial data. My macro view is predicated on forward-looking external risks (geopolitics, competition from AMD/custom silicon) that are not yet reflected in the financial statements but are signaled by the news.",
     'market_technical': "I assign a lower weight to the market_technical agent's long-term 'Bullish' stance. While the 'Intact Bullish Trend Structure' is a factual, backward-looking observation, my thesis is that the long-term competitive and geopolitical risks I've identified are the very catalysts that could eventually break this trend. The current trend does not invalidate the future risks."},
    'revised_short_term_stance': 'Neutral',
    'revised_long_term_stance': 'Bearish',
    'revised_confidence': 0.6,
    'revision_rationale': "I am revising my short-term stance from 'Bullish' to 'Neutral'. While my original view was correct that the earnings news was a strong bullish catalyst, the technical evidence shows this news is now priced in and the stock is consolidating. My long-term 'Bearish' stance is maintained; the exceptional fundamental data only strengthens the bull case that my contrarian view is based against, highlighting how much the market is ignoring the external risks I see. Confidence is slightly reduced from 0.65 to 0.60 to reflect that the overwhelming fundamental strength makes the timing of the long-term bearish thesis more uncertain.",
    'evidence_needed': ["Future earnings reports from AMD to quantify market share gains in the data center, validating the materiality of the 'Meta win'.",
     'Commentary from other hyperscalers (Google, Amazon, Microsoft) regarding their GPU supplier diversification and custom silicon development timelines.',
     "Updated satellite imagery or supply chain intelligence on the progress of Intel's foundry build-out to assess the viability of the TSM de-risking thesis."]},
   {'response_type': 'revision',
    'agreement': {'news_macro': "I agree with the news_macro agent's key evidence that Nvidia delivered a strong earnings and guidance beat that exceeded expectations. This information was missing from my original analysis and is a critical short-term bullish catalyst.",
     'market_technical': "I agree with the market_technical agent's assessment that the long-term trend structure remains bullish (price above key moving averages, relative outperformance), which aligns with my fundamental view. I also concur with the observation of a short-term consolidation/pullback (MACD crossover, drawdown), which provides a technical context for the market's reaction to the strong news."},
    'disagreement': {'news_macro': "I disagree with the news_macro agent's 'Bearish' long-term stance. While I acknowledge the validity of the identified risks (competitive pressure from AMD/Meta, geopolitical risks via TSM), I believe these are headwinds rather than thesis-breaking developments at this stage. The agent underweights Nvidia's current market dominance, technological lead, and the sheer scale of the AI-driven demand, which remain the primary drivers of the long-term fundamental outlook.",
     'market_technical': 'No significant disagreement. The technical analysis provides a useful, non-conflicting overlay to the fundamental picture.'},
    'revised_short_term_stance': 'Bullish',
    'revised_long_term_stance': 'Bullish',
    'revised_confidence': 0.8,
    'revision_rationale': "My original Neutral short-term stance and moderate confidence were driven by a lack of information on whether Nvidia beat expectations or provided strong guidance. The news_macro agent's evidence directly filled this gap, confirming a strong beat-and-raise. This transforms the short-term outlook from uncertain to clearly positive, justifying a shift to a Bullish stance and a significant increase in confidence. The long-term risks highlighted by the news_macro agent are now incorporated into my risk assessment but are not significant enough to alter the fundamental long-term Bullish thesis at this time.",
    'evidence_needed': ["Quantification of the financial impact of the AMD/Meta deal on Nvidia's future revenue and margin forecasts.",
     "Breakdown of Nvidia's customer concentration to assess the risk of hyperscalers developing more in-house or dual-source solutions.",
     'Management commentary from the earnings call specifically addressing the competitive landscape with AMD and the long-term strategy for mitigating customer concentration risk.',
     "Further analysis on the resilience of Nvidia's supply chain to potential disruptions related to TSM and Taiwan."]},
   {'response_type': 'revision',
    'agreement': ['I agree with the news_macro agent that the reported strong earnings and guidance beat is a significant positive catalyst that is likely to resolve the recent consolidation to the upside. This directly addresses my original concern about weakening short-term momentum.',
     "I agree with the fundamental agent's data showing 'exceptionally strong' quarter-over-quarter growth in revenue, net income, and free cash flow. This provides quantitative validation for the bullish narrative and reinforces the strength of the underlying long-term trend."],
    'disagreement': ["I assign a lower weight to the news_macro agent's long-term Bearish stance. While the competitive and geopolitical risks cited are valid fundamental concerns, my technical analysis shows the long-term uptrend is still firmly intact (price above key moving averages, relative outperformance). As a technical agent, I must prioritize the existing price trend until it shows clear signs of reversal.",
     "I disagree with the fundamental agent's short-term Neutral stance. Their neutrality stems from a lack of context (analyst estimates, guidance), which the news_macro agent's evidence provides by confirming a strong beat and guidance. The combination of stellar fundamental results and a positive news catalyst is a bullish short-term signal, not a neutral one."],
    'revised_short_term_stance': 'Bullish',
    'revised_long_term_stance': 'Bullish',
    'revised_confidence': 0.85,
    'evidence_needed': ['The official earnings release detailing specific EPS and Revenue figures versus analyst consensus estimates.',
     'The official management guidance figures for the upcoming quarter and fiscal year.',
     "The full earnings call transcript to analyze management's tone and commentary, particularly regarding the competitive and geopolitical risks highlighted by the news_macro agent."]}]},
 'reason_for_final_decision': "CIO Override: I am overriding the deterministic guardrail's long-term 'Bullish' stance to 'Neutral'. The guardrail's mechanically-weighted conclusion, despite a weak score (0.43), underweights the compelling, forward-looking risks identified by the news_macro agent. The fundamental and technical data are backward-looking and reflect a phenomenal, but potentially peaking, situation. The news_macro agent's thesis on competition (AMD/Meta) and geopolitics (TSM) represents a credible, structural threat to the long-term bull case. A 'Neutral' long-term stance and 'Hold / Monitor' action better reflect this critical tension between stellar current results and significant, unpriced future risks.",
 'agent_votes': {'short': [{'agent_name': 'news_macro',
    'stance': 'Neutral',
    'confidence': 0.6,
    'weight': 0.35,
    'contribution': 0.0},
   {'agent_name': 'fundamental',
    'stance': 'Bullish',
    'confidence': 0.8,
    'weight': 0.1,
    'contribution': 0.08},
   {'agent_name': 'market_technical',
    'stance': 'Bullish',
    'confidence': 0.85,
    'weight': 0.55,
    'contribution': 0.4675}],
  'long': [{'agent_name': 'news_macro',
    'stance': 'Bearish',
    'confidence': 0.6,
    'weight': 0.35,
    'contribution': -0.21},
   {'agent_name': 'fundamental',
    'stance': 'Bullish',
    'confidence': 0.8,
    'weight': 0.45,
    'contribution': 0.36},
   {'agent_name': 'market_technical',
    'stance': 'Bullish',
    'confidence': 0.85,
    'weight': 0.2,
    'contribution': 0.17}]},
 'scores': {'short': 0.7228, 'long': 0.4324},
 'llm_decision_used': True}

## Final Comparison: CIO vs Agents and External Baselines

This cell compares CIO against the three single agents and any external baseline CSVs saved under:

- `baseline_gpt.csv`
- `baseline_gemini.csv`
- `baseline_claude.csv`

In [45]:
comparison_bundle = q4.compare_with_external_baselines(
    cio_eval,
    packets_by_ticker,
    cache_root=CACHE_ROOT,
    long_post_trading_days=LONG_POST_TRADING_DAYS,
    neutral_band=NEUTRAL_BAND,
)

comparison_eval = comparison_bundle["comparison_eval"]
strategy_summary_with_external = comparison_bundle["strategy_summary"]
strategy_bucket_summary_with_external = comparison_bundle["strategy_bucket_summary"]
external_vs_cio = comparison_bundle["external_vs_cio"]
bucket_winners = comparison_bundle["bucket_winners"]
missing_external = comparison_bundle["missing_external"]

cio_row = strategy_summary_with_external[strategy_summary_with_external["strategy"] == "cio"].iloc[0]
best_short = strategy_summary_with_external.sort_values("short_accuracy", ascending=False).iloc[0]
best_long = strategy_summary_with_external.sort_values("long_accuracy", ascending=False).iloc[0]
external_text = "; ".join(
    f"{row.strategy}: short {row.short_accuracy:.1%} ({row.short_delta_vs_cio:+.1%} vs CIO), long {row.long_accuracy:.1%} ({row.long_delta_vs_cio:+.1%} vs CIO)"
    for row in external_vs_cio.itertuples(index=False)
)
missing_text = "".join(f"- Missing: `{item}`" for item in missing_external)

display(Markdown("### Overall Strategy Comparison"))
display(strategy_summary_with_external.sort_values("long_accuracy", ascending=False))

display(Markdown("### External Baselines vs CIO"))
display(external_vs_cio)

display(Markdown("### Bucket-Level Comparison"))
display(strategy_bucket_summary_with_external)

display(Markdown("### Best Strategy By Bucket"))
display(bucket_winners)

display(Markdown(f"""
### Takeaways

- CIO overall accuracy: **short {cio_row['short_accuracy']:.1%}**, **long {cio_row['long_accuracy']:.1%}**.
- Best short-horizon strategy: **{best_short.strategy}** at **{best_short.short_accuracy:.1%}**.
- Best long-horizon strategy: **{best_long.strategy}** at **{best_long.long_accuracy:.1%}**.
- External baseline comparison: {external_text if external_text else 'No external baseline files were loaded.'}
- Bucket winners show where CIO adds value versus where a single model/baseline is stronger. Use buckets with at least 3-4 cases for presentation-quality claims.

{missing_text}
"""))

### Overall Strategy Comparison

,strategy,short_evaluable,short_matched,short_accuracy,long_evaluable,long_matched,long_accuracy,short_delta_vs_cio,long_delta_vs_cio
2,market_technical,55,26,0.472727,55,31,0.563636,0.054545,0.018182
0,cio,55,23,0.418182,55,30,0.545455,0.000000,0.000000
1,news_macro,55,25,0.454545,55,29,0.527273,0.036364,-0.018182
5,gemini_baseline,55,19,0.345455,55,26,0.472727,-0.072727,-0.072727
4,gpt_baseline,55,26,0.472727,55,25,0.454545,0.054545,-0.090909
3,fundamental,55,7,0.127273,55,16,0.290909,-0.290909,-0.254545
6,claude_baseline,55,31,0.563636,55,11,0.200000,0.145455,-0.345455

### External Baselines vs CIO

,strategy,short_accuracy,short_delta_vs_cio,long_accuracy,long_delta_vs_cio,short_matched,short_evaluable,long_matched,long_evaluable
4,gpt_baseline,0.472727,0.054545,0.454545,-0.090909,26,55,25,55
5,gemini_baseline,0.345455,-0.072727,0.472727,-0.072727,19,55,26,55
6,claude_baseline,0.563636,0.145455,0.200000,-0.345455,31,55,11,55

### Bucket-Level Comparison

,bucket,cases,cio_short_accuracy,cio_long_accuracy,news_macro_short_accuracy,news_macro_long_accuracy,market_technical_short_accuracy,market_technical_long_accuracy,fundamental_short_accuracy,fundamental_long_accuracy,gpt_baseline_short_accuracy,gpt_baseline_long_accuracy,gemini_baseline_short_accuracy,gemini_baseline_long_accuracy,claude_baseline_short_accuracy,claude_baseline_long_accuracy
0,ai_infrastructure,9,0.555556,0.555556,0.555556,0.555556,0.555556,0.666667,0.111111,0.333333,0.444444,0.555556,0.666667,0.666667,0.555556,0.111111
1,ai_semis,13,0.538462,0.615385,0.461538,0.615385,0.692308,0.615385,0.153846,0.384615,0.538462,0.538462,0.076923,0.615385,0.615385,0.384615
2,data_center_operator,2,0.000000,0.500000,0.000000,0.500000,0.500000,0.500000,0.000000,0.500000,0.000000,0.500000,1.000000,0.500000,0.500000,0.000000
3,data_center_reit,4,0.250000,0.750000,0.500000,0.750000,0.250000,0.750000,0.250000,0.500000,0.500000,1.000000,0.500000,0.500000,0.500000,0.500000
4,mega_cap_platform,7,0.714286,0.285714,0.857143,0.428571,0.142857,0.142857,0.142857,0.285714,0.714286,0.285714,0.142857,0.285714,0.857143,0.285714
5,power_infrastructure,5,0.000000,0.600000,0.200000,0.600000,0.400000,0.600000,0.000000,0.200000,0.800000,0.600000,0.800000,0.600000,0.800000,0.000000
6,software_cloud,15,0.333333,0.533333,0.333333,0.400000,0.466667,0.600000,0.133333,0.133333,0.266667,0.200000,0.200000,0.266667,0.333333,0.066667

### Best Strategy By Bucket

,bucket,cases,best_short_strategy,best_short_accuracy,cio_short_accuracy,best_long_strategy,best_long_accuracy,cio_long_accuracy
0,ai_infrastructure,9,gemini_baseline,0.666667,0.555556,market_technical,0.666667,0.555556
1,ai_semis,13,market_technical,0.692308,0.538462,cio,0.615385,0.615385
2,data_center_operator,2,gemini_baseline,1.000000,0.000000,cio,0.500000,0.500000
3,data_center_reit,4,news_macro,0.500000,0.250000,gpt_baseline,1.000000,0.750000
4,mega_cap_platform,7,news_macro,0.857143,0.714286,news_macro,0.428571,0.285714
5,power_infrastructure,5,gpt_baseline,0.800000,0.000000,cio,0.600000,0.600000
6,software_cloud,15,market_technical,0.466667,0.333333,market_technical,0.600000,0.533333

### Takeaways

- CIO overall accuracy: **short 41.8%**, **long 54.5%**.
- Best short-horizon strategy: **claude_baseline** at **56.4%**.
- Best long-horizon strategy: **market_technical** at **56.4%**.
- External baseline comparison: gpt_baseline: short 47.3% (+5.5% vs CIO), long 45.5% (-9.1% vs CIO); gemini_baseline: short 34.5% (-7.3% vs CIO), long 47.3% (-7.3% vs CIO); claude_baseline: short 56.4% (+14.5% vs CIO), long 20.0% (-34.5% vs CIO)
- Bucket winners show where CIO adds value versus where a single model/baseline is stronger. Use buckets with at least 3-4 cases for presentation-quality claims.