# Expanded Q4 2025 AI/Tech Earnings Eval

This notebook runs or loads cached outputs for the expanded AI/Tech Q4 2025 earnings universe. Agent outputs are saved under `data/agent_outputs/q4_2025_ai_tech/` by agent type, so future runs can reuse them without calling the models again.

In [41]:
import os
import sys
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

CURRENT_DIR = Path.cwd().resolve()
REPO_ROOT = CURRENT_DIR if (CURRENT_DIR / "pyproject.toml").exists() else CURRENT_DIR.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
load_dotenv(REPO_ROOT / ".env", override=True)

from openclam.evaluation import q4_earnings_cache as q4
from openclam.agents.news_macro import news_macro_agent

print(f"Repo root: {REPO_ROOT}")
print(f"Cache root: {REPO_ROOT / q4.DEFAULT_CACHE_ROOT}")
print(f"VERTEX_PROJECT loaded: {bool(os.getenv('VERTEX_PROJECT') or os.getenv('GOOGLE_CLOUD_PROJECT'))}")
print(f"OPENAI_API_KEY loaded: {bool(os.getenv('OPENAI_API_KEY'))}")

Repo root: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory
Cache root: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech
VERTEX_PROJECT loaded: True
OPENAI_API_KEY loaded: False

## Configure Universe and Cache

Set `RUN_AGENTS=True` when you want to generate missing cached outputs. Keep `FORCE_RERUN=False` to reuse files that already exist.

In [42]:
import importlib
from openclam.evaluation import q4_earnings_cache as q4

q4 = importlib.reload(q4)

print(q4.__file__)
print(hasattr(q4, "q4_2025_combined_cio_advantage_df"))

/Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/src/openclam/evaluation/q4_earnings_cache.py
True

In [43]:
# Full combined Q4 2025 AI/Tech + CIO-advantage universe.
# This uses all tickers defined in q4_earnings_cache.py.
earnings_df = q4.q4_2025_combined_cio_advantage_df()

CACHE_ROOT = REPO_ROOT / q4.DEFAULT_CACHE_ROOT
RUN_AGENTS = True
FORCE_RERUN = False  # keep False: cached names will not rerun; only missing tickers are generated

PRE_TRADING_DAYS = 7
POST_TRADING_DAYS = 7
LONG_POST_TRADING_DAYS = 30
NEUTRAL_BAND = 0.02

VERTEX_PROJECT = os.getenv("VERTEX_PROJECT") or os.getenv("GOOGLE_CLOUD_PROJECT")
VERTEX_LOCATION = os.getenv("VERTEX_LOCATION", "us-central1")
VERTEX_MODEL = os.getenv("VERTEX_MODEL", "gemini-2.5-flash")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-nano")
NEWS_MODEL = os.getenv("NEWS_MODEL", "gpt-5.4-nano")
LLM_PROVIDER = "vertex" if VERTEX_PROJECT else "openai"

print("Full universe size:", len(earnings_df))
earnings_df

Full universe size: 55

,ticker,company,earnings_date,bucket
0,AAPL,Apple,2026-01-29,mega_cap_platform
1,MSFT,Microsoft,2026-01-28,mega_cap_platform
2,GOOGL,Alphabet,2026-02-03,mega_cap_platform
3,AMZN,Amazon,2026-02-05,mega_cap_platform
4,META,Meta Platforms,2026-01-28,mega_cap_platform
5,TSLA,Tesla,2026-01-28,mega_cap_platform
6,NVDA,Nvidia,2026-02-25,mega_cap_platform
7,AMD,Advanced Micro Devices,2026-02-03,ai_semis
8,AVGO,Broadcom,2026-03-05,ai_semis
9,MU,Micron Technology,2025-12-17,ai_semis
10,QCOM,Qualcomm,2026-02-04,ai_semis
11,ARM,Arm Holdings,2026-02-04,ai_semis
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,ai_semis
13,ASML,ASML Holding,2026-01-28,ai_semis
14,AMAT,Applied Materials,2026-02-12,ai_semis
15,LRCX,Lam Research,2026-01-28,ai_semis
16,KLAC,KLA,2026-01-29,ai_semis
17,ORCL,Oracle,2026-03-10,ai_infrastructure
18,DELL,Dell Technologies,2026-02-26,ai_infrastructure
19,SMCI,Super Micro Computer,2026-02-03,ai_infrastructure
20,ANET,Arista Networks,2026-02-17,ai_infrastructure
21,VRT,Vertiv,2026-02-18,ai_infrastructure
22,CRM,Salesforce,2026-02-25,software_cloud
23,ADBE,Adobe,2026-03-11,software_cloud
24,NOW,ServiceNow,2026-01-28,software_cloud
25,SNOW,Snowflake,2026-02-25,software_cloud
26,PLTR,Palantir,2026-02-03,software_cloud
27,DDOG,Datadog,2026-02-12,software_cloud
28,MDB,MongoDB,2026-03-04,software_cloud
29,NET,Cloudflare,2026-02-12,software_cloud
30,MRVL,Marvell Technology,2026-03-05,ai_semis
31,WDC,Western Digital,2026-01-29,ai_semis
32,STX,Seagate Technology,2026-01-21,ai_semis
33,COHR,Coherent,2026-02-05,ai_infrastructure
34,ALAB,Astera Labs,2026-02-10,ai_infrastructure
35,ETN,Eaton,2026-01-30,power_infrastructure
36,PWR,Quanta Services,2026-02-19,power_infrastructure
37,CEG,Constellation Energy,2026-02-19,power_infrastructure
38,NRG,NRG Energy,2026-02-27,power_infrastructure
39,GEV,GE Vernova,2026-01-22,power_infrastructure
40,EQIX,Equinix,2026-02-11,data_center_reit
41,DLR,Digital Realty,2026-02-12,data_center_reit
42,IRM,Iron Mountain,2026-02-20,data_center_reit
43,AMT,American Tower,2026-02-25,data_center_reit
44,CORZ,Core Scientific,2026-03-12,data_center_operator
45,IREN,IREN,2026-02-12,data_center_operator
46,CLS,Celestica,2026-01-27,ai_infrastructure
47,FLEX,Flex,2026-01-28,ai_infrastructure
48,TEAM,Atlassian,2026-01-29,software_cloud
49,ZS,Zscaler,2026-03-04,software_cloud
50,CRWD,CrowdStrike,2026-03-04,software_cloud
51,PANW,Palo Alto Networks,2026-02-12,software_cloud
52,OKTA,Okta,2026-03-03,software_cloud
53,APP,AppLovin,2026-02-12,software_cloud
54,SHOP,Shopify,2026-02-11,software_cloud

## Build Price Eval Table

In [44]:
summary_df, paths_df = q4.build_price_tables(
    earnings_df=earnings_df,
    cache_root=CACHE_ROOT,
    pre_trading_days=PRE_TRADING_DAYS,
    post_trading_days=POST_TRADING_DAYS,
    long_post_trading_days=LONG_POST_TRADING_DAYS,
)

news_macro_agent.format_return_columns(summary_df)

,ticker,company,earnings_date,pre_7d_return,post_1d_return,post_3d_return,post_7d_return,post_30d_return,full_window_return,full_30d_window_return,...,spy_post_30d_return,abnormal_30d_vs_spy,qqq_post_7d_return,abnormal_vs_qqq,qqq_post_30d_return,abnormal_30d_vs_qqq,realized_direction_vs_qqq,realized_30d_direction_vs_qqq,long_horizon_trading_days,bucket
0,AAPL,Apple,2026-01-29,4.69%,0.46%,4.34%,6.43%,-3.07%,11.42%,1.48%,...,-4.57%,1.51%,-2.40%,8.83%,-5.67%,2.60%,up,up,30,mega_cap_platform
1,MSFT,Microsoft,2026-01-28,4.73%,-9.99%,-12.10%,-16.71%,-16.37%,-12.77%,-12.41%,...,-4.22%,-12.15%,-3.72%,-12.99%,-5.68%,-10.69%,down,down,30,mega_cap_platform
2,GOOGL,Alphabet,2026-02-03,3.59%,-1.96%,-4.96%,-9.04%,-9.36%,-5.77%,-6.11%,...,-4.08%,-5.29%,-2.58%,-6.46%,-3.51%,-5.86%,down,down,30,mega_cap_platform
3,AMZN,Amazon,2026-02-05,-8.99%,-5.55%,-7.06%,-9.67%,-7.78%,-17.79%,-16.07%,...,-4.03%,-3.75%,0.72%,-10.39%,-2.51%,-5.27%,down,down,30,mega_cap_platform
4,META,Meta Platforms,2026-01-28,7.82%,10.40%,5.63%,-1.09%,-4.57%,6.64%,2.89%,...,-4.22%,-0.35%,-3.72%,2.64%,-5.68%,1.11%,up,up,30,mega_cap_platform
5,TSLA,Tesla,2026-01-28,-1.38%,-3.45%,-2.24%,-4.72%,-8.45%,-6.03%,-9.71%,...,-4.22%,-4.23%,-3.72%,-0.99%,-5.68%,-2.77%,down,down,30,mega_cap_platform
6,NVDA,Nvidia,2026-02-25,6.97%,-5.46%,-6.69%,-9.07%,-5.95%,-2.73%,0.61%,...,-1.64%,-4.31%,-2.75%,-6.33%,-0.93%,-5.02%,down,down,30,mega_cap_platform
7,AMD,Advanced Micro Devices,2026-02-03,-6.77%,-17.31%,-13.91%,-14.94%,-17.62%,-20.69%,-23.19%,...,-4.08%,-13.54%,-2.58%,-12.36%,-3.51%,-14.11%,down,down,30,ai_semis
8,AVGO,Broadcom,2026-03-05,2.24%,-0.69%,2.95%,-2.36%,22.42%,-0.18%,25.16%,...,4.52%,17.91%,-1.40%,-0.96%,6.69%,15.73%,down,up,30,ai_semis
9,MU,Micron Technology,2025-12-17,-8.67%,10.21%,22.65%,30.58%,94.21%,19.26%,77.38%,...,3.88%,90.33%,3.54%,27.04%,4.42%,89.79%,up,up,30,ai_semis
10,QCOM,Qualcomm,2026-02-04,-3.64%,-8.46%,-6.69%,-5.50%,-11.26%,-8.94%,-14.49%,...,-3.85%,-7.42%,-0.63%,-4.87%,-2.10%,-9.16%,down,down,30,ai_semis
11,ARM,Arm Holdings,2026-02-04,-8.57%,5.70%,18.79%,19.43%,23.76%,9.20%,13.15%,...,-3.85%,27.60%,-0.63%,20.06%,-2.10%,25.86%,up,up,30,ai_semis
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,4.34%,0.22%,-4.54%,-0.97%,8.04%,3.33%,12.73%,...,-0.85%,8.89%,1.50%,-2.47%,-2.20%,10.24%,down,up,30,ai_semis
13,ASML,ASML Holding,2026-01-28,4.74%,2.27%,1.30%,-0.70%,-4.89%,4.01%,-0.38%,...,-4.22%,-0.67%,-3.72%,3.03%,-5.68%,0.79%,up,up,30,ai_semis
14,AMAT,Applied Materials,2026-02-12,3.05%,8.08%,12.46%,15.23%,2.80%,18.74%,5.94%,...,-6.67%,9.47%,1.20%,14.03%,-6.22%,9.02%,up,up,30,ai_semis
15,LRCX,Lam Research,2026-01-28,7.45%,3.59%,-0.87%,-3.58%,-12.45%,3.61%,-5.93%,...,-4.22%,-8.23%,-3.72%,0.15%,-5.68%,-6.78%,up,down,30,ai_semis
16,KLAC,KLA,2026-01-29,13.36%,-15.24%,-19.54%,-14.52%,-15.68%,-3.10%,-4.42%,...,-4.57%,-11.11%,-2.40%,-12.12%,-5.67%,-10.01%,down,down,30,ai_semis
17,ORCL,Oracle,2026-03-10,2.75%,9.18%,3.82%,4.10%,25.94%,6.96%,29.41%,...,5.31%,20.63%,-2.43%,6.52%,7.93%,18.02%,up,up,30,ai_infrastructure
18,DELL,Dell Technologies,2026-02-26,4.62%,21.93%,19.54%,20.63%,46.40%,26.20%,53.16%,...,-1.16%,47.56%,-0.24%,20.88%,0.43%,45.97%,up,up,30,ai_infrastructure
19,SMCI,Super Micro Computer,2026-02-03,-6.40%,13.78%,15.87%,2.56%,2.29%,-4.01%,-4.26%,...,-4.08%,6.37%,-2.58%,5.14%,-3.51%,5.80%,up,up,30,ai_infrastructure
20,ANET,Arista Networks,2026-02-17,10.81%,-2.13%,-6.87%,-8.65%,-13.89%,1.23%,-4.58%,...,-4.50%,-9.39%,1.32%,-9.97%,-3.89%,-10.00%,down,down,30,ai_infrastructure
21,VRT,Vertiv,2026-02-18,24.35%,-0.06%,0.91%,4.80%,6.67%,30.33%,32.65%,...,-4.26%,10.93%,0.25%,4.55%,-3.42%,10.09%,up,up,30,ai_infrastructure
22,CRM,Salesforce,2026-02-25,1.07%,4.03%,0.63%,5.40%,-10.68%,6.53%,-9.72%,...,-1.64%,-9.03%,-2.75%,8.15%,-0.93%,-9.75%,up,down,30,software_cloud
23,ADBE,Adobe,2026-03-11,4.92%,-1.44%,-7.98%,-9.34%,-12.69%,-4.88%,-8.39%,...,5.04%,-17.72%,-4.22%,-5.12%,7.33%,-20.02%,down,down,30,software_cloud
24,NOW,ServiceNow,2026-01-28,1.81%,-9.94%,-8.96%,-22.28%,-12.85%,-20.87%,-11.26%,...,-4.22%,-8.62%,-3.72%,-18.56%,-5.68%,-7.17%,down,down,30,software_cloud
25,SNOW,Snowflake,2026-02-25,-7.18%,2.28%,0.66%,6.66%,-21.85%,-0.99%,-27.46%,...,-1.64%,-20.21%,-2.75%,9.41%,-0.93%,-20.92%,up,down,30,software_cloud
26,PLTR,Palantir,2026-02-03,-6.91%,-11.62%,-13.92%,-18.21%,-3.24%,-23.86%,-9.92%,...,-4.08%,0.84%,-2.58%,-15.63%,-3.51%,0.27%,down,up,30,software_cloud
27,DDOG,Datadog,2026-02-12,5.41%,-0.74%,-3.45%,-17.20%,-9.24%,-12.73%,-4.33%,...,-6.67%,-2.57%,1.20%,-18.41%,-6.22%,-3.02%,down,down,30,software_cloud
28,MDB,MongoDB,2026-03-04,-18.78%,6.42%,9.57%,5.04%,1.26%,-14.69%,-17.76%,...,2.69%,-1.43%,-2.79%,7.82%,5.00%,-3.74%,up,down,30,software_cloud
29,NET,Cloudflare,2026-02-12,8.73%,5.77%,3.39%,-11.54%,9.64%,-3.82%,19.21%,...,-6.67%,16.31%,1.20%,-12.74%,-6.22%,15.86%,down,up,30,software_cloud
30,MRVL,Marvell Technology,2026-03-05,-3.46%,18.35%,23.28%,21.01%,84.67%,16.83%,78.29%,...,4.52%,80.16%,-1.40%,22.41%,6.69%,77.98%,up,up,30,ai_semis
31,WDC,Western Digital,2026-01-29,24.86%,-10.12%,4.25%,2.72%,-2.15%,28.26%,22.18%,...,-4.57%,2.42%,-2.40%,5.12%,-5.67%,3.52%,up,up,30,ai_semis
32,STX,Seagate Technology,2026-01-21,13.23%,0.67%,4.09%,18.44%,6.72%,34.10%,20.83%,...,-0.60%,7.31%,0.91%,17.53%,-1.20%,7.91%,up,up,30,ai_semis
33,COHR,Coherent,2026-02-05,-2.22%,8.81%,9.14%,5.12%,21.21%,2.79%,18.52%,...,-4.03%,25.24%,0.72%,4.41%,-2.51%,23.72%,up,up,30,ai_infrastructure
34,ALAB,Astera Labs,2026-02-10,21.40%,-21.41%,-29.28%,-29.08%,-34.20%,-13.90%,-20.11%,...,-4.84%,-29.35%,-0.44%,-28.65%,-3.75%,-30.45%,down,down,30,ai_infrastructure
35,ETN,Eaton,2026-01-30,3.98%,2.28%,3.86%,7.41%,3.06%,11.69%,7.16%,...,-3.32%,6.37%,-1.67%,9.09%,-3.46%,6.51%,up,up,30,power_infrastructure
36,PWR,Quanta Services,2026-02-19,7.66%,-0.24%,2.56%,3.37%,1.22%,11.29%,8.97%,...,-3.92%,5.14%,0.77%,2.60%,-2.94%,4.16%,up,up,30,power_infrastructure
37,CEG,Constellation Energy,2026-02-19,7.17%,1.09%,7.19%,12.17%,-6.33%,20.21%,0.38%,...,-3.92%,-2.41%,0.77%,11.41%,-2.94%,-3.39%,up,down,30,power_infrastructure
38,NRG,NRG Energy,2026-02-27,4.62%,-1.89%,-8.62%,-13.30%,-4.87%,-9.30%,-0.48%,...,0.29%,-5.16%,0.08%,-13.38%,1.79%,-6.66%,down,down,30,power_infrastructure
39,GEV,GE Vernova,2026-01-22,3.42%,-0.59%,4.69%,14.10%,19.28%,18.01%,23.36%,...,-2.41%,21.69%,0.87%,13.23%,-3.38%,22.66%,up,up,30,power_infrastructure
40,EQIX,Equinix,2026-02-11,7.05%,10.41%,9.73%,9.00%,11.66%,16.69%,19.53%,...,-6.52%,18.18%,-1.91%,10.91%,-6.30%,17.95%,up,up,30,data_center_reit
41,DLR,Digital Realty,2026-02-12,9.64%,0.37%,-2.38%,-1.15%,-2.05%,8.39%,7.40%,...,-6.67%,4.62%,1.20%,-2.35%,-6.22%,4.17%,down,up,30,data_center_reit
42,IRM,Iron Mountain,2026-02-20,11.06%,0.82%,1.35%,-2.28%,-4.61%,8.53%,5.94%,...,-4.16%,-0.44%,-1.19%,-1.09%,-3.21%,-1.39%,down,down,30,data_center_reit
43,AMT,American Tower,2026-02-25,-5.01%,1.39%,4.23%,3.35%,-1.40%,-1.83%,-6.34%,...,-1.64%,0.24%,-2.75%,6.09%,-0.93%,-0.47%,up,down,30,data_center_reit
44,CORZ,Core Scientific,2026-03-12,6.14%,1.54%,1.11%,2.09%,28.57%,8.37%,36.47%,...,7.48%,21.09%,-1.43%,3.52%,11.29%,17.28%,up,up,30,data_center_operator
45,IREN,IREN,2026-02-12,-26.40%,5.47%,5.12%,13.54%,-12.34%,-16.44%,-35.48%,...,-6.67%,-5.67%,1.20%,12.34%,-6.22%,-6.12%,up,down,30,data_center_operator
46,CLS,Celestica,2026-01-27,6.26%,3.62%,-15.66%,-11.49%,-20.22%,-5.95%,-15.22%,...,-2.75%,-17.47%,-5.40%,-6.09%,-3.71%,-16.51%,down,down,30,ai_infrastructure
47,FLEX,Flex,2026-01-28,2.22%,-1.21%,-2.40%,-3.46%,-4.48%,-1.31%,-2.36%,...,-4.22%,-0.26%,-3.72%,0.27%,-5.68%,1.20%,up,up,30,ai_infrastructure
48,TEAM,Atlassian,2026-01-29,1.97%,-1.83%,-12.78%,-24.21%,-37.52%,-22.73%,-36.30%,...,-4.57%,-32.95%,-2.40%,-21.81%,-5.67%,-31.85%,down,down,30,software_cloud
49,ZS,Zscaler,2026-03-04,9.02%,3.68%,4.10%,-1.57%,-14.01%,7.31%,-6.25%,...,2.69%,-16.70%,-2.79%,1.22%,5.00%,-19.01%,up,down,30,software_cloud
50,CRWD,CrowdStrike,2026-03-04,16.37%,4.53%,6.49%,8.36%,2.58%,26.10%,19.37%,...,2.69%,-0.11%,-2.79%,11.15%,5.00%,-2.42%,up,down,30,software_cloud
51,PANW,Palo Alto Networks,2026-02-12,-2.06%,2.54%,-6.42%,-12.98%,-9.70%,-14.78%,-11.56%,...,-6.67%,-3.03%,1.20%,-14.19%,-6.22%,-3.48%,down,down,30,software_cloud
52,OKTA,Okta,2026-03-03,-2.38%,-1.08%,11.31%,8.87%,-7.13%,6.27%,-9.34%,...,3.16%,-10.29%,-0.72%,9.58%,6.09%,-13.22%,up,down,30,software_cloud
53,APP,AppLovin,2026-02-12,-20.55%,6.44%,10.22%,7.17%,3.89%,-14.85%,-17.45%,...,-6.67%,10.57%,1.20%,5.97%,-6.22%,10.11%,up,up,30,software_cloud
54,SHOP,Shopify,2026-02-11,-10.20%,-6.78%,-4.36%,-1.20%,-2.76%,-11.29%,-12.69%,...,-6.52%,3.76%,-1.91%,0.70%,-6.30%,3.53%,up,up,30,software_cloud

## Run or Load Cached Agent Outputs

In [47]:
if RUN_AGENTS:
    packets_by_ticker, errors_by_ticker = q4.run_q4_2025_universe_agents(
        earnings_df=earnings_df,
        cache_root=CACHE_ROOT,
        force=FORCE_RERUN,
        lookback_days=14,
        max_news=10,
        llm_provider=LLM_PROVIDER,
        vertex_project=VERTEX_PROJECT,
        vertex_location=VERTEX_LOCATION,
        vertex_model=VERTEX_MODEL,
        openai_model=OPENAI_MODEL,
        news_model=NEWS_MODEL,
    )
else:
    packets_by_ticker = q4.load_cached_packets_by_ticker(CACHE_ROOT)
    errors_by_ticker = {}

print("cached/available tickers:", sorted(packets_by_ticker))
errors_by_ticker

cached/available tickers: ['AAPL', 'ADBE', 'ALAB', 'AMAT', 'AMD', 'AMT', 'AMZN', 'ANET', 'APP', 'ARM', 'ASML', 'AVGO', 'CEG', 'CLS', 'COHR', 'CORZ', 'CRM', 'CRWD', 'DDOG', 'DELL', 'DLR', 'EQIX', 'ETN', 'FLEX', 'GEV', 'GOOGL', 'IREN', 'IRM', 'KLAC', 'LRCX', 'MDB', 'META', 'MRVL', 'MSFT', 'MU', 'NET', 'NOW', 'NRG', 'NVDA', 'OKTA', 'ORCL', 'PANW', 'PLTR', 'PWR', 'QCOM', 'SHOP', 'SMCI', 'SNOW', 'STX', 'TEAM', 'TSLA', 'TSM', 'VRT', 'WDC', 'ZS']

{'AAPL': {},
 'MSFT': {},
 'GOOGL': {},
 'AMZN': {},
 'META': {},
 'TSLA': {},
 'NVDA': {},
 'AMD': {},
 'AVGO': {},
 'MU': {},
 'QCOM': {},
 'ARM': {},
 'TSM': {},
 'ASML': {},
 'AMAT': {},
 'LRCX': {},
 'KLAC': {},
 'ORCL': {},
 'DELL': {},
 'SMCI': {},
 'ANET': {},
 'VRT': {},
 'CRM': {},
 'ADBE': {},
 'NOW': {},
 'SNOW': {},
 'PLTR': {},
 'DDOG': {},
 'MDB': {},
 'NET': {},
 'MRVL': {},
 'WDC': {},
 'STX': {},
 'COHR': {},
 'ALAB': {},
 'ETN': {},
 'PWR': {},
 'CEG': {},
 'NRG': {},
 'GEV': {},
 'EQIX': {},
 'DLR': {},
 'IRM': {},
 'AMT': {},
 'CORZ': {},
 'IREN': {},
 'CLS': {},
 'FLEX': {},
 'TEAM': {},
 'ZS': {},
 'CRWD': {},
 'PANW': {},
 'OKTA': {},
 'APP': {},
 'SHOP': {}}

## Run CIO Eval From Cached Packets

In [48]:
expected_tickers = set(summary_df["ticker"].str.upper())

cached_cio_files = {
    path.stem.upper()
    for path in (CACHE_ROOT / "cio").glob("*.json")
}

missing_cio_tickers = sorted(expected_tickers - cached_cio_files)

print("Missing CIO tickers:", missing_cio_tickers)

incremental_results = {}

for ticker in missing_cio_tickers:
    print("\n" + "=" * 80)
    print(f"Running CIO for {ticker}...")
    print("=" * 80)

    one_summary_df = summary_df[
        summary_df["ticker"].str.upper() == ticker
    ].copy()

    one_packets = {
        ticker: packets_by_ticker.get(ticker, [])
    }

    if not one_packets[ticker]:
        print(f"Skipped {ticker}: no packets found.")
        continue

    try:
        one_cio_eval, one_cio_results, one_cio_summary = q4.run_cached_cio_eval(
            one_summary_df,
            one_packets,
            cache_root=CACHE_ROOT,
            long_post_trading_days=LONG_POST_TRADING_DAYS,
            neutral_band=NEUTRAL_BAND,
            use_llm_debate=True,
            use_llm_decision=True,
            llm_provider=LLM_PROVIDER,
            debate_model=VERTEX_MODEL if VERTEX_PROJECT else OPENAI_MODEL,
            decision_model=VERTEX_MODEL if VERTEX_PROJECT else OPENAI_MODEL,
            vertex_project=VERTEX_PROJECT,
            vertex_location=VERTEX_LOCATION,
        )

        incremental_results[ticker] = one_cio_results.get(ticker)
        print(f"Saved CIO result for {ticker}: {CACHE_ROOT / 'cio' / f'{ticker}.json'}")

    except Exception as exc:
        print(f"Failed CIO for {ticker}: {repr(exc)}")

Missing CIO tickers: ['ADBE', 'ARM', 'DDOG', 'KLAC', 'MDB', 'NET', 'NOW', 'QCOM', 'SMCI', 'SNOW']

================================================================================
Running CIO for ADBE...
================================================================================
Saved CIO result for ADBE: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/ADBE.json

================================================================================
Running CIO for ARM...
================================================================================
Saved CIO result for ARM: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/ARM.json

================================================================================
Running CIO for DDOG...
================================================================================
Saved CIO result for DDOG: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/DDOG.json

================================================================================
Running CIO for KLAC...
================================================================================
Saved CIO result for KLAC: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/KLAC.json

================================================================================
Running CIO for MDB...
================================================================================
Saved CIO result for MDB: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/MDB.json

================================================================================
Running CIO for NET...
================================================================================
Saved CIO result for NET: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/NET.json

================================================================================
Running CIO for NOW...
================================================================================
Saved CIO result for NOW: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/NOW.json

================================================================================
Running CIO for QCOM...
================================================================================
Saved CIO result for QCOM: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/QCOM.json

================================================================================
Running CIO for SMCI...
================================================================================
Saved CIO result for SMCI: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/SMCI.json

================================================================================
Running CIO for SNOW...
================================================================================
Saved CIO result for SNOW: /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/SNOW.json

In [49]:
# Rebuild full cio_eval from all cached CIO workflows for the current summary_df universe

expected_tickers = set(summary_df["ticker"].str.upper())

cio_results = {
    path.stem.upper(): q4.load_json(path)
    for path in (CACHE_ROOT / "cio").glob("*.json")
    if path.stem.upper() in expected_tickers
}

print("Expected tickers:", len(expected_tickers))
print("Loaded cached CIO workflows:", len(cio_results))
print("Missing cached CIO workflows:", sorted(expected_tickers - set(cio_results)))

def stance_to_direction(stance):
    if stance == "Bullish":
        return "up"
    if stance == "Bearish":
        return "down"
    return None

def match_direction(predicted, realized, abnormal, neutral_band=0.02):
    if pd.isna(abnormal) or realized is None:
        return None
    abnormal = float(abnormal)
    if predicted is None:
        return abs(abnormal) <= neutral_band
    return predicted == realized

def match_reason(predicted, realized, abnormal, neutral_band=0.02):
    if pd.isna(abnormal) or realized is None:
        return "missing realized abnormal return"
    abnormal = float(abnormal)
    if predicted is None:
        if abs(abnormal) <= neutral_band:
            return "neutral matched: abnormal return stayed inside neutral band"
        return "neutral missed: abnormal return moved outside neutral band"
    return "matched" if predicted == realized else "missed"

long_abnormal_col = f"abnormal_{LONG_POST_TRADING_DAYS}d_vs_qqq"
long_direction_col = f"realized_{LONG_POST_TRADING_DAYS}d_direction_vs_qqq"

rows = []

for _, row in summary_df.iterrows():
    ticker = row["ticker"].upper()
    workflow = cio_results.get(ticker)
    base = row.to_dict()

    if not workflow:
        base.update({
            "cio_ready": False,
            "cio_short_term_stance": None,
            "cio_long_term_stance": None,
            "cio_action": None,
            "cio_confidence": None,
            "cio_debate_triggered": None,
            "cio_debate_conflict_level": None,
            "cio_reason": "missing cached CIO workflow",
            "cio_short_direction_match": None,
            "cio_short_direction_match_reason": "missing cached CIO workflow",
            "cio_long_direction_match": None,
            "cio_long_direction_match_reason": "missing cached CIO workflow",
        })
        rows.append(base)
        continue

    decision = workflow["final_decision"]
    debate = workflow["debate"]

    short_stance = decision["final_short_term_stance"]
    long_stance = decision["final_long_term_stance"]

    short_pred = stance_to_direction(short_stance)
    long_pred = stance_to_direction(long_stance)

    base.update({
        "cio_ready": True,
        "cio_short_term_stance": short_stance,
        "cio_long_term_stance": long_stance,
        "cio_action": decision.get("investment_action"),
        "cio_confidence": decision.get("confidence"),
        "cio_debate_triggered": debate.get("triggered"),
        "cio_debate_conflict_level": debate.get("trigger", {}).get("conflict_level"),
        "cio_reason": decision.get("reason_for_final_decision"),
        "cio_short_direction_match": match_direction(
            short_pred,
            row.get("realized_direction_vs_qqq"),
            row.get("abnormal_vs_qqq"),
            NEUTRAL_BAND,
        ),
        "cio_short_direction_match_reason": match_reason(
            short_pred,
            row.get("realized_direction_vs_qqq"),
            row.get("abnormal_vs_qqq"),
            NEUTRAL_BAND,
        ),
        "cio_long_direction_match": match_direction(
            long_pred,
            row.get(long_direction_col),
            row.get(long_abnormal_col),
            NEUTRAL_BAND,
        ),
        "cio_long_direction_match_reason": match_reason(
            long_pred,
            row.get(long_direction_col),
            row.get(long_abnormal_col),
            NEUTRAL_BAND,
        ),
    })

    rows.append(base)

cio_eval = pd.DataFrame(rows)

cio_summary = {
    "overall": {
        "cases": int(len(cio_eval)),
        "cio_ready_cases": int((cio_eval["cio_ready"] == True).sum()),
        "debate_trigger_rate": float((cio_eval["cio_debate_triggered"] == True).mean()),
        "cio_short_direction_match_evaluable": int(cio_eval["cio_short_direction_match"].notna().sum()),
        "cio_short_direction_match_matched": int((cio_eval["cio_short_direction_match"] == True).sum()),
        "cio_short_direction_match_accuracy": float(
            (cio_eval[cio_eval["cio_short_direction_match"].notna()]["cio_short_direction_match"] == True).mean()
        ),
        "cio_long_direction_match_evaluable": int(cio_eval["cio_long_direction_match"].notna().sum()),
        "cio_long_direction_match_matched": int((cio_eval["cio_long_direction_match"] == True).sum()),
        "cio_long_direction_match_accuracy": float(
            (cio_eval[cio_eval["cio_long_direction_match"].notna()]["cio_long_direction_match"] == True).mean()
        ),
    },
    "by_bucket": q4.summarize_cio_eval_by_bucket(cio_eval),
}

cio_eval.to_csv(CACHE_ROOT / "tables" / "cio_eval_combined_cache_aware.csv", index=False)
q4.save_json(CACHE_ROOT / "tables" / "cio_eval_combined_cache_aware_summary.json", cio_summary)

print(cio_summary)
news_macro_agent.format_return_columns(cio_eval)

Expected tickers: 55
Loaded cached CIO workflows: 55
Missing cached CIO workflows: []
{'overall': {'cases': 55, 'cio_ready_cases': 55, 'debate_trigger_rate': 0.6, 'cio_short_direction_match_evaluable': 55, 'cio_short_direction_match_matched': 20, 'cio_short_direction_match_accuracy': 0.36363636363636365, 'cio_long_direction_match_evaluable': 55, 'cio_long_direction_match_matched': 30, 'cio_long_direction_match_accuracy': 0.5454545454545454}, 'by_bucket': {'ai_infrastructure': {'cases': 9, 'debate_trigger_rate': 0.6666666666666666, 'short_accuracy': 0.3333333333333333, 'long_accuracy': 0.5555555555555556, 'avg_confidence': 0.7594444444444445}, 'ai_semis': {'cases': 13, 'debate_trigger_rate': 0.3076923076923077, 'short_accuracy': 0.38461538461538464, 'long_accuracy': 0.6153846153846154, 'avg_confidence': 0.8230769230769232}, 'data_center_operator': {'cases': 2, 'debate_trigger_rate': 0.5, 'short_accuracy': 0.0, 'long_accuracy': 0.5, 'avg_confidence': 0.7}, 'data_center_reit': {'cases': 4, 'debate_trigger_rate': 0.25, 'short_accuracy': 0.25, 'long_accuracy': 0.75, 'avg_confidence': 0.75}, 'mega_cap_platform': {'cases': 7, 'debate_trigger_rate': 0.8571428571428571, 'short_accuracy': 0.7142857142857143, 'long_accuracy': 0.2857142857142857, 'avg_confidence': 0.7928571428571428}, 'power_infrastructure': {'cases': 5, 'debate_trigger_rate': 0.6, 'short_accuracy': 0.2, 'long_accuracy': 0.6, 'avg_confidence': 0.764}, 'software_cloud': {'cases': 15, 'debate_trigger_rate': 0.8, 'short_accuracy': 0.3333333333333333, 'long_accuracy': 0.5333333333333333, 'avg_confidence': 0.7733333333333332}}}

,ticker,company,earnings_date,pre_7d_return,post_1d_return,post_3d_return,post_7d_return,post_30d_return,full_window_return,full_30d_window_return,...,cio_long_term_stance,cio_action,cio_confidence,cio_debate_triggered,cio_debate_conflict_level,cio_reason,cio_short_direction_match,cio_short_direction_match_reason,cio_long_direction_match,cio_long_direction_match_reason
0,AAPL,Apple,2026-01-29,4.69%,0.46%,4.34%,6.43%,-3.07%,11.42%,1.48%,...,Neutral,Watch / No Trade,0.750,True,high,"As CIO, I am ratifying the committee's unanimo...",True,matched,False,neutral missed: abnormal return moved outside ...
1,MSFT,Microsoft,2026-01-28,4.73%,-9.99%,-12.10%,-16.71%,-16.37%,-12.77%,-12.41%,...,Bullish,Accumulate on Weakness,0.850,True,high,The committee reached a unanimous post-debate ...,True,matched,False,missed
2,GOOGL,Alphabet,2026-02-03,3.59%,-1.96%,-4.96%,-9.04%,-9.36%,-5.77%,-6.11%,...,Bullish,Wait for pullback,0.750,False,low,I am adopting a final view that aligns with th...,True,matched,False,missed
3,AMZN,Amazon,2026-02-05,-8.99%,-5.55%,-7.06%,-9.67%,-7.78%,-17.79%,-16.07%,...,Bullish,Wait for pullback to initiate position,0.900,True,high,This decision overrides the deterministic guar...,True,matched,False,missed
4,META,Meta Platforms,2026-01-28,7.82%,10.40%,5.63%,-1.09%,-4.57%,6.64%,2.89%,...,Bullish,Accumulate on weakness,0.750,True,high,An override of the initial purely technical or...,False,missed,True,matched
5,TSLA,Tesla,2026-01-28,-1.38%,-3.45%,-2.24%,-4.72%,-8.45%,-6.03%,-9.71%,...,Bearish,Short / Avoid,0.800,True,high,The decision is based on a unanimous post-deba...,True,matched,True,matched
6,NVDA,Nvidia,2026-02-25,6.97%,-5.46%,-6.69%,-9.07%,-5.95%,-2.73%,0.61%,...,Neutral,Long,0.750,True,high,This decision represents a CIO override of the...,False,missed,False,neutral missed: abnormal return moved outside ...
7,AMD,Advanced Micro Devices,2026-02-03,-6.77%,-17.31%,-13.91%,-14.94%,-17.62%,-20.69%,-23.19%,...,Bullish,Wait for Pullback,0.900,True,high,I am confirming the guardrail's stances but up...,True,matched,False,missed
8,AVGO,Broadcom,2026-03-05,2.24%,-0.69%,2.95%,-2.36%,22.42%,-0.18%,25.16%,...,Bullish,Buy,0.850,False,low,The final decision is an override of the guard...,False,missed,True,matched
9,MU,Micron Technology,2025-12-17,-8.67%,10.21%,22.65%,30.58%,94.21%,19.26%,77.38%,...,Bullish,Long,0.900,False,low,The committee reached a high-conviction bullis...,True,matched,True,matched
10,QCOM,Qualcomm,2026-02-04,-3.64%,-8.46%,-6.69%,-5.50%,-11.26%,-8.94%,-14.49%,...,Bullish,Wait for Pullback / Scale In,0.750,False,low,The committee's decision is an override of the...,True,matched,False,missed
11,ARM,Arm Holdings,2026-02-04,-8.57%,5.70%,18.79%,19.43%,23.76%,9.20%,13.15%,...,Neutral,Avoid / Do Not Initiate,0.800,True,high,This decision is an override of the determinis...,False,missed,False,neutral missed: abnormal return moved outside ...
12,TSM,Taiwan Semiconductor Manufacturing,2026-01-15,4.34%,0.22%,-4.54%,-0.97%,8.04%,3.33%,12.73%,...,Bullish,Long,0.900,False,low,The committee's decision is Bullish on both sh...,False,missed,True,matched
13,ASML,ASML Holding,2026-01-28,4.74%,2.27%,1.30%,-0.70%,-4.89%,4.01%,-0.38%,...,Bullish,Wait for Pullback,0.800,False,low,The final decision aligns with the determinist...,False,missed,True,matched
14,AMAT,Applied Materials,2026-02-12,3.05%,8.08%,12.46%,15.23%,2.80%,18.74%,5.94%,...,Bullish,Watch / Accumulate on Weakness,0.700,False,low,The committee's final view is a short-term Neu...,False,neutral missed: abnormal return moved outside ...,True,matched
15,LRCX,Lam Research,2026-01-28,7.45%,3.59%,-0.87%,-3.58%,-12.45%,3.61%,-5.93%,...,Bullish,Long,0.900,False,low,I am overriding the 'Neutral' short-term stanc...,True,matched,False,missed
16,KLAC,KLA,2026-01-29,13.36%,-15.24%,-19.54%,-14.52%,-15.68%,-3.10%,-4.42%,...,Bullish,Long,0.800,False,low,I am overriding the deterministic guardrail's ...,False,missed,False,missed
17,ORCL,Oracle,2026-03-10,2.75%,9.18%,3.82%,4.10%,25.94%,6.96%,29.41%,...,Bullish,Long,0.850,True,high,This is a clear case of a CIO override on posi...,True,matched,True,matched
18,DELL,Dell Technologies,2026-02-26,4.62%,21.93%,19.54%,20.63%,46.40%,26.20%,53.16%,...,Bullish,Long,0.850,False,low,The committee reached a unanimous 'Bullish' lo...,True,matched,True,matched
19,SMCI,Super Micro Computer,2026-02-03,-6.40%,13.78%,15.87%,2.56%,2.29%,-4.01%,-4.26%,...,Neutral,Long,0.585,True,high,The committee reached a unanimous short-term B...,True,matched,False,neutral missed: abnormal return moved outside ...
20,ANET,Arista Networks,2026-02-17,10.81%,-2.13%,-6.87%,-8.65%,-13.89%,1.23%,-4.58%,...,Bullish,Long,0.800,False,low,The committee is unanimously Bullish on the lo...,False,missed,False,missed
21,VRT,Vertiv,2026-02-18,24.35%,-0.06%,0.91%,4.80%,6.67%,30.33%,32.65%,...,Bullish,Hold / Do Not Initiate New Position,0.850,True,high,I am upholding the deterministic guardrail's '...,False,neutral missed: abnormal return moved outside ...,True,matched
22,CRM,Salesforce,2026-02-25,1.07%,4.03%,0.63%,5.40%,-10.68%,6.53%,-9.72%,...,Bearish,Avoid / Short,0.700,False,low,I am confirming the deterministic guardrail's ...,False,missed,True,matched
23,ADBE,Adobe,2026-03-11,4.92%,-1.44%,-7.98%,-9.34%,-12.69%,-4.88%,-8.39%,...,Neutral,Watch / No Trade,0.800,True,high,I am adopting the unanimous post-debate short-...,True,matched,False,neutral missed: abnormal return moved outside ...
24,NOW,ServiceNow,2026-01-28,1.81%,-9.94%,-8.96%,-22.28%,-12.85%,-20.87%,-11.26%,...,Bullish,Accumulate on weakness,0.850,True,high,The final decision aligns with the determinist...,True,matched,False,missed
25,SNOW,Snowflake,2026-02-25,-7.18%,2.28%,0.66%,6.66%,-21.85%,-0.99%,-27.46%,...,Bearish,Avoid / Do Not Add,0.800,False,low,The decision is to adopt a Bearish stance on b...,False,missed,True,matched
26,PLTR,Palantir,2026-02-03,-6.91%,-11.62%,-13.92%,-18.21%,-3.24%,-23.86%,-9.92%,...,Bullish,Long,0.850,True,high,The final decision is an override of the initi...,False,missed,True,matched
27,DDOG,Datadog,2026-02-12,5.41%,-0.74%,-3.45%,-17.20%,-9.24%,-12.73%,-4.33%,...,Bullish,Wait for Pullback,0.700,True,high,The decision is a direct synthesis of the post...,True,matched,False,missed
28,MDB,MongoDB,2026-03-04,-18.78%,6.42%,9.57%,5.04%,1.26%,-14.69%,-17.76%,...,Bearish,Short / Avoid,0.900,True,high,This decision aligns with the deterministic gu...,False,missed,True,matched
29,NET,Cloudflare,2026-02-12,8.73%,5.77%,3.39%,-11.54%,9.64%,-3.82%,19.21%,...,Neutral,Hold / Tactical Buy,0.800,True,high,"As CIO, I concur with the committee's unanimou...",False,missed,False,neutral missed: abnormal return moved outside ...
30,MRVL,Marvell Technology,2026-03-05,-3.46%,18.35%,23.28%,21.01%,84.67%,16.83%,78.29%,...,Bullish,Buy,0.850,False,low,The decision is to upgrade the confidence in t...,True,matched,True,matched
31,WDC,Western Digital,2026-01-29,24.86%,-10.12%,4.25%,2.72%,-2.15%,28.26%,22.18%,...,Bullish,Accumulate on Dips,0.800,True,high,I am overriding the guardrail's 'Bullish' shor...,False,neutral missed: abnormal return moved outside ...,True,matched
32,STX,Seagate Technology,2026-01-21,13.23%,0.67%,4.09%,18.44%,6.72%,34.10%,20.83%,...,Bullish,Watch / Wait for Pullback,0.750,True,high,The committee reached a unanimous and coherent...,False,neutral missed: abnormal return moved outside ...,True,matched
33,COHR,Coherent,2026-02-05,-2.22%,8.81%,9.14%,5.12%,21.21%,2.79%,18.52%,...,Bullish,Wait for Pullback,0.750,False,low,The CIO has overridden the guardrail's 'Bearis...,False,neutral missed: abnormal return moved outside ...,True,matched
34,ALAB,Astera Labs,2026-02-10,21.40%,-21.41%,-29.28%,-29.08%,-34.20%,-13.90%,-20.11%,...,Bullish,Watch / Accumulate on Weakness,0.850,True,high,I am upholding the guardrail's Neutral short-t...,False,neutral missed: abnormal return moved outside ...,False,missed
35,ETN,Eaton,2026-01-30,3.98%,2.28%,3.86%,7.41%,3.06%,11.69%,7.16%,...,Bullish,Wait for pullback,0.700,True,high,The committee reached a unanimous post-debate ...,False,missed,True,matched
36,PWR,Quanta Services,2026-02-19,7.66%,-0.24%,2.56%,3.37%,1.22%,11.29%,8.97%,...,Bullish,"Initiate a starter position, add on any pullba...",0.770,False,low,The committee's final decision is to adopt a B...,True,matched,True,matched
37,CEG,Constellation Energy,2026-02-19,7.17%,1.09%,7.19%,12.17%,-6.33%,20.21%,0.38%,...,Bullish,Wait for pullback,0.850,True,high,The final decision is an override of the initi...,False,missed,False,missed
38,NRG,NRG Energy,2026-02-27,4.62%,-1.89%,-8.62%,-13.30%,-4.87%,-9.30%,-0.48%,...,Bullish,Accumulate on Weakness,0.800,True,high,This decision constitutes a tactical override ...,False,neutral missed: abnormal return moved outside ...,False,missed
39,GEV,GE Vernova,2026-01-22,3.42%,-0.59%,4.69%,14.10%,19.28%,18.01%,23.36%,...,Bullish,Wait for pullback to accumulate,0.700,False,low,The committee's final view synthesizes the age...,False,neutral missed: abnormal return moved outside ...,True,matched
40,EQIX,Equinix,2026-02-11,7.05%,10.41%,9.73%,9.00%,11.66%,16.69%,19.53%,...,Bullish,Accumulate on Weakness,0.800,False,low,The committee's final decision is to override ...,False,neutral missed: abnormal return moved outside ...,True,matched
41,DLR,Digital Realty,2026-02-12,9.64%,0.37%,-2.38%,-1.15%,-2.05%,8.39%,7.40%,...,Bullish,Accumulate on Weakness,0.700,False,low,I am overriding the deterministic guardrail's ...,False,neutral missed: abnormal return moved outside ...,True,matched
42,IRM,Iron Mountain,2026-02-20,11.06%,0.82%,1.35%,-2.28%,-4.61%,8.53%,5.94%,...,Bullish,Watch / Add on Weakness,0.800,True,high,The committee reached a strong post-debate con...,True,neutral matched: abnormal return stayed inside...,False,missed
43,AMT,American Tower,2026-02-25,-5.01%,1.39%,4.23%,3.35%,-1.40%,-1.83%,-6.34%,...,Neutral,Avoid / Reduce,0.700,False,low,The committee adopts a Bearish short-term stan...,False,missed,True,neutral matched: abnormal return stayed inside...
44,CORZ,Core Scientific,2026-03-12,6.14%,1.54%,1.11%,2.09%,28.57%,8.37%,36.47%,...,Bullish,Wait for pullback,0.600,False,low,The committee's final decision is to adopt a '...,False,neutral missed: abnormal return moved outside ...,True,matched
45,IREN,IREN,2026-02-12,-26.40%,5.47%,5.12%,13.54%,-12.34%,-16.44%,-35.48%,...,Bullish,Wait for Pullback,0.800,True,high,I am overriding the guardrail's 'Normal' posit...,False,missed,False,missed
46,CLS,Celestica,2026-01-27,6.26%,3.62%,-15.66%,-11.49%,-20.22%,-5.95%,-15.22%,...,Bullish,Hold / Do Not Add,0.600,True,high,This is an override of the deterministic guard...,False,neutral missed: abnormal return moved outside ...,False,missed
47,FLEX,Flex,2026-01-28,2.22%,-1.21%,-2.40%,-3.46%,-4.48%,-1.31%,-2.36%,...,Bullish,Wait for pullback,0.700,True,high,This final view represents a CIO override of t...,False,missed,True,matched
48,TEAM,Atlassian,2026-01-29,1.97%,-1.83%,-12.78%,-24.21%,-37.52%,-22.73%,-36.30%,...,Bearish,Avoid / Do Not Add,0.600,True,high,This decision overrides the guardrail's short-...,False,neutral missed: abnormal return moved outside ...,True,matched
49,ZS,Zscaler,2026-03-04,9.02%,3.68%,4.10%,-1.57%,-14.01%,7.31%,-6.25%,...,Bearish,Avoid,0.600,False,low,The deterministic guardrail recommended a Bear...,False,missed,True,matched
50,CRWD,CrowdStrike,2026-03-04,16.37%,4.53%,6.49%,8.36%,2.58%,26.10%,19.37%,...,Bullish,Hold / Accumulate on Weakness,0.700,True,high,Override of the guardrail's short-term 'Bullis...,False,neutral missed: abnormal return moved outside ...,False,missed
51,PANW,Palo Alto Networks,2026-02-12,-2.06%,2.54%,-6.42%,-12.98%,-9.70%,-14.78%,-11.56%,...,Bearish,Avoid / Short,0.850,True,high,I am overriding the initial mixed signals from...,True,matched,True,matched
52,OKTA,Okta,2026-03-03,-2.38%,-1.08%,11.31%,8.87%,-7.13%,6.27%,-9.34%,...,Bullish,Long,0.700,True,high,The final decision is to adopt a Bullish stanc...,True,matched,False,missed
53,APP,AppLovin,2026-02-12,-20.55%,6.44%,10.22%,7.17%,3.89%,-14.85%,-17.45%,...,Bullish,Accumulate on Weakness,0.850,True,high,I am overriding the guardrail's confidence and...,False,missed,True,matched
54,SHOP,Shopify,2026-02-11,-10.20%,-6.78%,-4.36%,-1.20%,-2.76%,-11.29%,-12.69%,...,Bearish,Short / Avoid,0.900,True,high,This is a high-conviction decision to override...,False,missed,False,missed

## Inspect Saved Outputs

In [50]:
ticker_to_inspect = "NVDA"
cached = q4.load_cached_ticker(ticker_to_inspect, CACHE_ROOT)
print("saved files:")
for key, value in q4.cached_ticker_paths(ticker_to_inspect, CACHE_ROOT).items():
    print(key, value)

packets = cached.get("packets") or []
packet_df = pd.DataFrame(packets)
display_cols = ["agent_name", "short_term_stance", "long_term_stance", "confidence", "stance_rationale"]
packet_df[[col for col in display_cols if col in packet_df.columns]]

saved files:
news_macro /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/news_macro/NVDA.json
market_technical /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/market_technical/NVDA.json
fundamental /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/fundamental/NVDA.json
packets /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/packets/NVDA.json
cio /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/cio/NVDA.json
context /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/contexts/NVDA.json
errors /Users/zhang/Github/OpenClam_Multi-Agent_Investment_Advisory/data/agent_outputs/q4_2025_ai_tech/errors/NVDA.json

,agent_name,short_term_stance,long_term_stance,confidence,stance_rationale
0,news_macro,Bullish,Bearish,0.65,The short-term stance is Bullish due to a dire...
1,market_technical,Neutral,Bullish,0.85,The dominant technical feature is the conflict...
2,fundamental,Neutral,Bullish,0.60,NVIDIA reported an exceptionally strong quarte...

In [51]:
# Debate trace for one ticker
workflow = cio_results.get(ticker_to_inspect) or q4.load_json(CACHE_ROOT / "cio" / f"{ticker_to_inspect}.json")
pd.DataFrame(workflow["debate"].get("debate_responses", []))

,response_type,agreement,disagreement,revised_short_term_stance,revised_long_term_stance,revised_confidence,evidence_needed
0,agent_revision,{'fundamental_agent': 'I agree with the fundam...,{'market_technical_agent': 'I assign lower wei...,Bullish,Bearish,0.7,"[To invalidate the long-term bearish thesis, I..."
1,revision,{'news_macro': 'I agree with the news_macro ag...,{'news_macro': 'I assign lower weight to the n...,Bullish,Bullish,0.9,[Confirmation of a price breakout above the re...
2,agent_view_revision,[I agree with the news_macro agent's primary e...,[I disagree with the news_macro agent's long-t...,Bullish,Bullish,0.8,[Quantitative data on data center market share...

# Baseline

- always_bullish
- earnings_day_momentum：after financial report if post_1d_return > 0 then Bullish，else Bearish

In [52]:
import pandas as pd
import numpy as np

def stance_to_direction(stance):
    stance = str(stance).lower()
    if stance == "bullish":
        return "up"
    if stance == "bearish":
        return "down"
    return None

def direction_match(predicted_direction, realized_direction, abnormal_return, neutral_band=0.02):
    if predicted_direction is None or realized_direction is None or pd.isna(abnormal_return):
        return None

    abnormal_return = float(abnormal_return)

    if abs(abnormal_return) <= neutral_band:
        return predicted_direction is None

    return predicted_direction == realized_direction

def eval_baseline(
    df,
    short_stance_col,
    long_stance_col,
    prefix,
    long_post_trading_days=30,
    neutral_band=0.02,
):
    out = df.copy()

    short_pred_col = f"{prefix}_short_predicted_direction"
    long_pred_col = f"{prefix}_long_predicted_direction"
    short_match_col = f"{prefix}_short_direction_match"
    long_match_col = f"{prefix}_long_direction_match"

    long_abnormal_col = f"abnormal_{long_post_trading_days}d_vs_qqq"
    long_direction_col = f"realized_{long_post_trading_days}d_direction_vs_qqq"

    out[short_pred_col] = out[short_stance_col].apply(stance_to_direction)
    out[long_pred_col] = out[long_stance_col].apply(stance_to_direction)

    out[short_match_col] = out.apply(
        lambda row: direction_match(
            row[short_pred_col],
            row["realized_direction_vs_qqq"],
            row["abnormal_vs_qqq"],
            neutral_band=neutral_band,
        ),
        axis=1,
    )

    out[long_match_col] = out.apply(
        lambda row: direction_match(
            row[long_pred_col],
            row[long_direction_col],
            row[long_abnormal_col],
            neutral_band=neutral_band,
        ),
        axis=1,
    )

    return out

def summarize_match(df, short_col, long_col):
    short_eval = df[df[short_col].notna()]
    long_eval = df[df[long_col].notna()]

    return {
        "short_evaluable": int(len(short_eval)),
        "short_matched": int((short_eval[short_col] == True).sum()),
        "short_accuracy": float((short_eval[short_col] == True).mean()) if len(short_eval) else None,
        "long_evaluable": int(len(long_eval)),
        "long_matched": int((long_eval[long_col] == True).sum()),
        "long_accuracy": float((long_eval[long_col] == True).mean()) if len(long_eval) else None,
    }

baseline_eval = cio_eval.copy()

# Baseline 1: Always Bullish
baseline_eval["always_bullish_short_stance"] = "Bullish"
baseline_eval["always_bullish_long_stance"] = "Bullish"

baseline_eval = eval_baseline(
    baseline_eval,
    short_stance_col="always_bullish_short_stance",
    long_stance_col="always_bullish_long_stance",
    prefix="always_bullish",
    long_post_trading_days=LONG_POST_TRADING_DAYS,
    neutral_band=NEUTRAL_BAND,
)

# Baseline 2: Earnings-day momentum
# If the stock is up after earnings day, assume continuation; if down, assume continuation down.
baseline_eval["earnings_momentum_short_stance"] = np.where(
    baseline_eval["post_1d_return"] > 0,
    "Bullish",
    "Bearish",
)
baseline_eval["earnings_momentum_long_stance"] = baseline_eval["earnings_momentum_short_stance"]

baseline_eval = eval_baseline(
    baseline_eval,
    short_stance_col="earnings_momentum_short_stance",
    long_stance_col="earnings_momentum_long_stance",
    prefix="earnings_momentum",
    long_post_trading_days=LONG_POST_TRADING_DAYS,
    neutral_band=NEUTRAL_BAND,
)

baseline_summary = {
    "cio": {
        "short_accuracy": cio_summary["overall"]["cio_short_direction_match_accuracy"],
        "long_accuracy": cio_summary["overall"]["cio_long_direction_match_accuracy"],
    },
    "always_bullish": summarize_match(
        baseline_eval,
        "always_bullish_short_direction_match",
        "always_bullish_long_direction_match",
    ),
    "earnings_day_momentum": summarize_match(
        baseline_eval,
        "earnings_momentum_short_direction_match",
        "earnings_momentum_long_direction_match",
    ),
}

baseline_summary

{'cio': {'short_accuracy': 0.36363636363636365,
  'long_accuracy': 0.5454545454545454},
 'always_bullish': {'short_evaluable': 55,
  'short_matched': 28,
  'short_accuracy': 0.509090909090909,
  'long_evaluable': 55,
  'long_matched': 23,
  'long_accuracy': 0.41818181818181815},
 'earnings_day_momentum': {'short_evaluable': 55,
  'short_matched': 38,
  'short_accuracy': 0.6909090909090909,
  'long_evaluable': 55,
  'long_matched': 33,
  'long_accuracy': 0.6}}

In [53]:
bucket_rows = []

for bucket, group in baseline_eval.groupby("bucket"):
    row = {"bucket": bucket, "cases": len(group)}

    row.update({
        "cio_short_accuracy": float((group["cio_short_direction_match"] == True).mean()),
        "cio_long_accuracy": float((group["cio_long_direction_match"] == True).mean()),
    })

    row.update({
        "always_bullish_short_accuracy": float((group["always_bullish_short_direction_match"] == True).mean()),
        "always_bullish_long_accuracy": float((group["always_bullish_long_direction_match"] == True).mean()),
        "earnings_momentum_short_accuracy": float((group["earnings_momentum_short_direction_match"] == True).mean()),
        "earnings_momentum_long_accuracy": float((group["earnings_momentum_long_direction_match"] == True).mean()),
    })

    bucket_rows.append(row)

baseline_bucket_summary = pd.DataFrame(bucket_rows)
baseline_bucket_summary

,bucket,cases,cio_short_accuracy,cio_long_accuracy,always_bullish_short_accuracy,always_bullish_long_accuracy,earnings_momentum_short_accuracy,earnings_momentum_long_accuracy
0,ai_infrastructure,9,0.333333,0.555556,0.555556,0.555556,0.666667,0.666667
1,ai_semis,13,0.384615,0.615385,0.538462,0.615385,0.692308,0.692308
2,data_center_operator,2,0.000000,0.500000,1.000000,0.500000,1.000000,0.500000
3,data_center_reit,4,0.250000,0.750000,0.500000,0.500000,0.500000,0.500000
4,mega_cap_platform,7,0.714286,0.285714,0.285714,0.142857,0.857143,0.857143
5,power_infrastructure,5,0.200000,0.600000,0.800000,0.600000,0.600000,0.400000
6,software_cloud,15,0.333333,0.533333,0.400000,0.200000,0.666667,0.466667

The CIO layer adds the clearest value in AI semiconductors over the 30-trading-day horizon, where it outperforms both always-bullish and earnings-day momentum baselines. This suggests that multi-agent synthesis is most useful when post-earnings performance depends on interpreting supply-chain, capex, and second-order AI infrastructure signals. For mega-cap platform stocks, however, earnings-day momentum is a stronger baseline, implying that near-term capital flows and benchmark positioning dominate multi-agent fundamental reasoning.